## TensorFlow


https://www.tensorflow.org/

https://www.tensorflow.org/tutorials

(https://www.iitg.ac.in/cseweb/osint/iNN-week-3.php)

What are TensorFlow?

TensorFlow is general purpose Python programming language based open-source end-toend platform Developed by Google Brain Team for creating Machine Learning applications.
It is one of the most popular programming platform for high dimensional computation and
implementing complex deep learning models

TensorFlow 2.0

• Eager execution, allowing to build the models and run instantly.
• Keras, high-level API for different Deep Learning Models, is incorporated with TensorFlow 2.0.
• Using Keras API, building complex deep learning models becomes a trivial task
• The size of the program becomes much smaller in 2.0 as compared to 1.0

What are Tensors?


A tensor is an algebraic object that describes a multilinear relationship between sets of
algebraic objects related to a vector space.
Wikipedia:
In short, tensors are generalization of scalars and vectors

0d Tensor 1d Tensor 2d Tensor 3d Tensor 4d Tensor

https://www.iitg.ac.in/cseweb/osint/slides/course1/Lesson%2015.pdf

In [2]:
# Types of Tensors?
import tensorflow as tf

# Create a zero-dimensional tensor
scalar = tf.constant(5)
print(scalar)  # Output: tf.Tensor(5, shape=(), dtype=int32)

ModuleNotFoundError: No module named 'tensorflow.python.distribute.distribution_strategy_context'

In [ ]:
# 2. One-Dimensional Tensors (Vectors)
# A one-dimensional tensor is a list of numbers, also known as a vector.

import tensorflow as tf

# Create a one-dimensional tensor
vector = tf.constant([1, 2, 3, 4, 5])
print(vector)  # Output: tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)

In [ ]:
# 3. Two-Dimensional Tensors (Matrices)
# A two-dimensional tensor is a table of numbers, also known as a matrix.


# Create a two-dimensional tensor
matrix = tf.constant([[1, 2, 3], [4, 5, 6]])
print(matrix)  # Output: tf.Tensor([[1 2 3], [4 5 6]], shape=(2, 3), dtype=int32)

In [ ]:
# 4. Three-Dimensional Tensors (Cubes)
# A three-dimensional tensor is a cube of numbers.

import tensorflow as tf

# Create a three-dimensional tensor
cube = tf.constant([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(cube)  # Output: tf.Tensor([[[ 1  2  3], [ 4  5  6]], [[ 7  8  9], [10 11 12]]], shape=(2, 2, 3), dtype=int32)


In [ ]:
# 5. Higher-Dimensional Tensors
# Higher-dimensional tensors can be created by adding more dimensions to the tensor.
import tensorflow as tf

# Create a four-dimensional tensor
four_d_tensor = tf.constant([[[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]], [[[13, 14, 15], [16, 17, 18]], [[19, 20, 21], [22, 23, 24]]]])
print(four_d_tensor)  # Output: tf.Tensor([[[[ 1  2  3], [ 4  5  6]], [[ 7  8  9], [10 11 12]]], [[[13 14 15], [16 17 18]], [[19 20 21], [22 23 24]]]], shape=(2, 2, 2, 3), dtype=int32)

In [ ]:
# 6. Sparse Tensors
# Sparse tensors are used to represent tensors with a large number of zero values.
import tensorflow as tf

# Create a sparse tensor
sparse_tensor = tf.sparse.SparseTensor(indices=[[0, 0], [1, 2]], values=[1, 2], dense_shape=[3, 4])
print(sparse_tensor)  # Output: SparseTensor(indices=tf.Tensor([[0 0], [1 2]], shape=(2, 2), dtype=int64), values=tf.Tensor([1 2], shape=(2,), dtype=int32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))


In [ ]:
# Ragged Tensors
# Ragged tensors are used to represent tensors with variable-length rows.
import tensorflow as tf

# Create a ragged tensor
ragged_tensor = tf.ragged.constant([[1, 2, 3], [4, 5], [6]])
print(ragged_tensor)  # Output: tf.RaggedTensor([[1, 2, 3], [4, 5], [6]])