In [1]:
# pip install numpy

In [1]:
import numpy
import numpy as np
# what is numpy
# use case or feature of numpy
# numpy is a library for the Python programming language, adding support for large, multi-dimensional arrays and
# matrices, along with a large collection of high-level mathematical functions to operate on these arrays.

# numpy vs list
# numpy is faster and more memory efficient than lists for large datasets.
# numpy arrays are more suitable for numerical computations.
# numpy arrays are more suitable for scientific computing.
# numpy arrays are more suitable for data analysis.
# numpy arrays are more suitable for machine learning.
# numpy arrays are more suitable for data science.

# what is array
# use case or feature of array
# An array is a collection of elements of the same data type stored in contiguous memory locations.
# Arrays are used to store and manipulate large amounts of data.

Why is the Numpy Array so Fast?

Numpy arrays are written mostly in C language. Being written in C, the arrays are stored in contiguous memory locations which makes them accessible and easier to manipulate. This means that you can get the performance level of a C code with the ease of writing a Python program.

- Homogeneous Data: Arrays store elements of the same data type, making them more compact and memory-efficient than lists.
- Fixed Data Type: Arrays have a fixed data type, reducing memory overhead by eliminating the need to store type information for each element.
- Contiguous Memory: Arrays store elements in adjacent memory locations, reducing fragmentation and allowing for efficient access.

In [4]:
import numpy as np

a = np.array(5)

In [10]:
arr = np.array([2,3,4,5,6,7,8,9])
arr

array([2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
print(a)

5


In [8]:
type(a)

numpy.ndarray

In [25]:
l1 =['007x',12,12.4,True]

In [24]:
type(l1)
arr1 =np.array(l1)
arr1

array(['ab767867yuiyiiuyiyuuiyuiyiuyiuyuyi6877887x', '12', '12.4', 'True'],
      dtype='<U42')

In [12]:
type(l1[0])

str

In [13]:
type(l1[2])

float

In [16]:
type(arr[2])

numpy.int64

In [26]:
arr

array([2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
arr[5]= 23
arr

array([ 2,  3,  4,  5,  6, 23,  8,  9])

In [29]:
# sliceing
l1

['007x', 12, 12.4, True]

In [32]:
l1[start:end:step]

['007x', 12, 12.4, True]

In [33]:
l1[:2]

['007x', 12]

In [30]:
l1[:2]

['007x', 12]

In [31]:
arr[:2]

array([2, 3])

In [34]:
arr[-1]

np.int64(9)

In [38]:
arr[-4::2]

array([6, 8])

In [44]:
arr3 =np.arange(1,7)
arr3

array([1, 2, 3, 4, 5, 6])

In [45]:
arr4= np.arange(11,16)
arr4

array([11, 12, 13, 14, 15])

In [46]:
arr3+arr4

ValueError: operands could not be broadcast together with shapes (6,) (5,) 

In [47]:
arr3.ndim

1