In [1]:
# pip install numpy

In [1]:
import numpy
import numpy as np
# what is numpy
# use case or feature of numpy
# numpy is a library for the Python programming language, adding support for large, multi-dimensional arrays and
# matrices, along with a large collection of high-level mathematical functions to operate on these arrays.

# numpy vs list
# numpy is faster and more memory efficient than lists for large datasets.
# numpy arrays are more suitable for numerical computations.
# numpy arrays are more suitable for scientific computing.
# numpy arrays are more suitable for data analysis.
# numpy arrays are more suitable for machine learning.
# numpy arrays are more suitable for data science.

# what is array
# use case or feature of array
# An array is a collection of elements of the same data type stored in contiguous memory locations.
# Arrays are used to store and manipulate large amounts of data.

Why is the Numpy Array so Fast?

Numpy arrays are written mostly in C language. Being written in C, the arrays are stored in contiguous memory locations which makes them accessible and easier to manipulate. This means that you can get the performance level of a C code with the ease of writing a Python program.

- Homogeneous Data: Arrays store elements of the same data type, making them more compact and memory-efficient than lists.
- Fixed Data Type: Arrays have a fixed data type, reducing memory overhead by eliminating the need to store type information for each element.
- Contiguous Memory: Arrays store elements in adjacent memory locations, reducing fragmentation and allowing for efficient access.

## NumPy Array Creation

In [ ]:
# NumPy Array Creation
# An array allows us to store a collection of multiple values in a single data structure.
# The NumPy array is similar to a list, but with added benefits such as being faster and more memory efficient.
# Numpy library provides various methods to work with data. To leverage all those features, we first need to create numpy arrays.
# There are multiple techniques to generate arrays in NumPy

In [5]:
import numpy as np
# Create NumPy Array from a List
li = [1,2,3,4]

numpyArr = np.array(li)
numpyArr


array([1, 2, 3, 4])

In [4]:
# direct create array
arr = np.array([1, 2, 3, 4, 5])

print(arr)
  
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
https://algebra1course.wordpress.com/2013/02/19/3-matrix-operations-dot-products-and-inverses/

https://www.geeksforgeeks.org/numpy-array-in-python/?ref=lbp

https://www.codementor.io/@innat_2k14/image-data-analysis-using-numpy-opencv-part-1-kfadbafx6

https://www.kdnuggets.com/2020/01/convert-picture-numbers.html

https://www.tomasbeuzen.com/python-programming-for-data-science/chapters/chapter6-numpy-addendum.html

https://stackoverflow.com/questions/66355882/how-to-convert-rgb-values-from-txt-file-to-display-an-image-in-python

https://knowledge.dataiku.com/latest/ml-analytics/nlp/concept-text-features-for-ml.html 


In [ ]:
# NumPy Creating Arrays
# Dimensions in Arrays
# A dimension in arrays is one level of array depth (nested arrays).

# 0-D Arrays
# 0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.

import numpy as np

arr = np.array(42)

print(arr)

# from tuple
tup = (1,2,3,4)
numpyArr = np.array(tup)

# 1-D Arrays
# An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.

arr = np.array([1, 2, 3, 4, 5])

# 2-D Arrays
# An array that has 1-D arrays as its elements is called a 2-D array.

# These are often used to represent matrix or 2nd order tensors.

#  2D
arr = np.array([[1, 2, 3], [4, 5, 6]])

# 3-D arrays
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

# Check Number of Dimensions
arr.ndim
# check dtypes
type(arr)
# Types of Array:
# One Dimensional Array
# Multi-Dimensional Array

arr = np.array([
                [[1, 2, 3], 
                 [4, 5, 6]], 
                 
                [[1, 2, 3], 
                 [4, 5, 6]]
                ])


sample_array = np.array([[0, 4, 2],
                       [3, 4, 5],
                       [23, 4, 5],
                       [2, 34, 5],
                       [5, 6, 7]])


Anatomy of an array :
1. Axis: The Axis of an array describes the order of the indexing into the array.

Axis 0 = one dimensional

Axis 1 = Two dimensional

Axis 2 = Three dimensional 

2. Shape: The number of elements along with each axis. It is from a tuple.
- sample_array.shape
3. Rank: The rank of an array is simply the number of axes (or dimensions) it has.
4. Data type objects (dtype): Data type objects (dtype) is an instance of numpy.dtype class. 

In [4]:
# 4. numpy.linspace(): This function returns evenly spaced numbers over a specified between two limits. 
np.linspace(0.0, 1, 4, dtype = np.float32)

array([0.        , 0.33333334, 0.6666667 , 1.        ], dtype=float32)

: 

In [ ]:
import numpy as np
# Some different way of creating Numpy Array :
# 1. numpy.array(): The Numpy array object in Numpy is called ndarray. We can create ndarray using numpy.array() function.
arr = np.array([3,4,5,5])


# 3. numpy.arange(): This is an inbuilt NumPy function that returns evenly spaced values within a given interval.
# Syntax: numpy.arange([start, ]stop, [step, ]dtype=None)
np.arange(1, 20 , 2,dtype = np.float32)

# 4. numpy.linspace(): This function returns evenly spaced numbers over a specified between two limits. 
np.linspace(0.0, 1, 4, dtype = np.int32)

# 5. numpy.empty(): This function create a new array of given shape and type, without initializing value.
# Syntax: numpy.empty(shape, dtype=float, order=’C’)
np.empty([4, 3],dtype = np.int32)

# 6. numpy.ones(): This function is used to get a new array of given shape and type, filled with ones(1).
# Syntax: numpy.ones(shape, dtype=None, order=’C’)
np.ones([4, 3],dtype = np.int32)

# 7. numpy.zeros(): This function is used to get a new array of given shape and type, filled with zeros(0). 
# Syntax: numpy.ones(shape, dtype=None)
np.zeros([4, 3], dtype = np.int32)

# Create a 2-D array with elements initialized to 5 
numpy_array = np.full((2, 2), 5)

# generate an array of 5 random numbers
array1 = np.random.rand(5)
np.random.randint(5,9,  size=(3,3))
np.random.random((3,4))
np.random.randn(3,4)
# create an empty array of length 4
array1 = np.empty(4)

# create a 2D array with 2 rows and 4 columns
array1 = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8]])

# create a 3D array with 2 "slices", each of 3 rows and 4 columns
array1 = np.array([[[1, 2, 3, 4],
                [5, 6, 7, 8], 
                [9, 10, 11, 12]],
                     
                [[13, 14, 15, 16], 
                 [17, 18, 19, 20], 
                 [21, 22, 23, 24]]])


In [ ]:
# Creating array object
arr = np.array( [[ 1, 2, 3],
                 [ 4, 2, 5]] )
 
# Printing type of arr object
print("Array is of type: ", type(arr))
 
# Printing array dimensions (axes)
print("No. of dimensions: ", arr.ndim)
 
# Printing shape of array
print("Shape of array: ", arr.shape)
 
# Printing size (total number of elements) of array
print("Size of array: ", arr.size)
 
# Printing type of elements in array
print("Array stores elements of type: ", arr.dtype)

## Check Data Type of NumPy Array

In [ ]:
import numpy as np

# create an array of  integers
int_array = np.array([-3, -1, 0, 1])

# create an array of floating-point numbers
float_array = np.array([0.1, 0.2, 0.3])

# create an array of complex numbers
complex_array = np.array([1+2j, 2+3j, 3+4j])

# check the data type of int_array
print(int_array.dtype)  # prints int64

# check the data type of float_array
print(float_array.dtype)  # prints float64

# check the data type of complex_array
print(complex_array.dtype)  # prints complex128

In [1]:
32*32

1024

##  Creating NumPy Arrays With a Defined Data Type

In [1]:
import numpy as np

# create an array of 8-bit integers
array1 = np.array([1, 3, 7], dtype='int8')

# create an array of unsigned 16-bit integers
array2 = np.array([2, 4, 6], dtype='uint16')

# create an array of 32-bit floating-point numbers
array3 = np.array([1.2, 2.3, 3.4], dtype='float32')

# create an array of 64-bit complex numbers
array4 = np.array([1+2j, 2+3j, 3+4j], dtype='complex64')

# print the arrays and their data types
print(array1, array1.dtype)
print(array2, array2.dtype)
print(array3, array3.dtype)
print(array4, array4.dtype)

[1 3 7] int8
[2 4 6] uint16
[1.2 2.3 3.4] float32
[1.+2.j 2.+3.j 3.+4.j] complex64


## NumPy Type Conversion

In NumPy, we can convert the data type of an array using the astype() method. For example,

In [2]:
# create an array of integers
int_array = np.array([1, 3, 5, 7])

# convert data type of int_array to float
float_array = int_array.astype('float')
    
# print the arrays and their data types
print(int_array, int_array.dtype)
print(float_array, float_array.dtype)

[1 3 5 7] int64
[1. 3. 5. 7.] float64


## NumPy Array Attributes

In NumPy, attributes are properties of NumPy arrays that provide information about the array's shape, size, data type, dimension


Attributes	Description

ndim	returns number of dimension of the array

size	returns number of elements in the array

dtype	returns data type of elements in the array

shape	returns the size of the array in each dimension.

itemsize	returns the size (in bytes) of each elements in the array

data	returns the buffer containing actual elements of the array in memory

In [3]:
import numpy as np

# create a default 1-D array of integers
array1 = np.array([6, 7, 8, 10, 13])

# create a 1-D array of 32-bit integers 
array2 = np.array([6, 7, 8, 10, 13], dtype=np.int32)

# use of itemsize to determine size of each array element of array1 and array2
print(array1.itemsize)  # prints 8
print(array2.itemsize)  # prints 4

# Here, the data attribute returns the memory addresses

8
4


## Array Indexing


In [6]:
import numpy as np

array1 = np.array([1, 3, 5, 7, 9])

# access numpy elements using index
print(array1[0])    # prints 1
print(array1[2])    # prints 5
print(array1[4])    # prints 9

array1 = np.array([2, 4, 6, 8, 10])
# change the value of the first element
array1[0] = 12
print("After modifying first element:",array1)    # prints [12 4 6 8 10]

# change the value of the third element
array1[2] = 14
print("After modifying third element:",array1)    # prints [12 4 14 8 10]


# Negative Array Indexing
# access the last element
print(array1[-1])    # prints 9

# access the second-to-last element
print(array1[-2])    # prints 7

# Modify Array Elements Using Negative Indexing
array1[-1] = 13

# 2-D NumPy Array Indexing


# create a 2D array 
array1 = np.array([[1, 3, 5, 7], 
                       [9, 11, 13, 15],
                       [2, 4, 6, 8]])

# access the element at the second row and fourth column
element1 = array1[1, 3]  # returns 15
print("4th Element at 2nd Row:",element1)  

# access the element at the first row and second column
element2 = array1[0, 1]  # returns 3
print("2nd Element at First Row:",element2)  
array1[1][0]

1
5
9
After modifying first element: [12  4  6  8 10]
After modifying third element: [12  4 14  8 10]
10
8
4th Element at 2nd Row: 15
2nd Element at First Row: 3


np.int64(9)

In [8]:
# Access Row or Column of 2D Array Using Indexing
import numpy as np

# create a 2D array 
array1 = np.array([[1, 3, 5], 
             [7, 9, 2], 
             [4, 6, 8]])

# access the second row of the array
second_row = array1[1, :]
print("Second Row:", second_row)  # Output: [7 9 2]

# access the third column of the array
third_col = array1[:, 2]
print("Third Column:", third_col)  # Output: [5 2 8]

Second Row: [7 9 2]
Third Column: [5 2]


In [12]:
# 3-D NumPy Array Indexing
# To access an element of a 3D array, we use three indices separated by commas.

# The first index refers to the slice
# The second index refers to the row
# The third index refers to the column.

import numpy as np

# create a 3D array with shape (2, 3, 4)
array1 = np.array([[[1, 2, 3, 4], 
                   [5, 6, 7, 8], 
                   [9, 10, 11, 12]],
                     
                    [[13, 14, 15, 16], 
                    [17, 18, 19, 20], 
                    [21, 22, 23, 24]]])

# access a specific element of the array
element = array1[1, 2, 1]

# print the value of the element
print(element) 
 
# Output: 22

array1[1, 2,2] # access the second 2D array, i.e.

22


np.int64(23)

# NumPy Array Slicing

In [ ]:
# Array Slicing is the process of extracting a portion of an array.
# array[start:stop:step]
# If we omit start, slicing starts from the first element
# If we omit stop, slicing continues up to the last element
# If we omit step, default step size is 1

In [3]:
# 1D NumPy Array Slicing
import numpy as np

# create a 1D array 
array1 = np.array([1, 3, 5, 7, 8, 9, 2, 4, 6])

# slice array1 from index 2 to index 6 (exclusive)
print(array1[2:6])  # [5 7 8 9]

# slice array1 from index 0 to index 8 (exclusive) with a step size of 2
print(array1[0:8:2])  # [1 5 8 2]

# slice array1 from index 3 up to the last element
print(array1[3:])  # [7 8 9 2 4 6]

# items from start to end
print(array1[:])   # [1 3 5 7 8 9 2 4 6]

# modify elements from indices 2 to 5
array1[2:5] = 22

# Negative Slicing
print(array1[-3:])    # [8 10 12]

# Reverse NumPy Array Using Negative Slicing
# generate reversed array
reversed_numbers = array1[::-1]
print(reversed_numbers)

[5 7 8 9]
[1 5 8 2]
[7 8 9 2 4 6]
[1 3 5 7 8 9 2 4 6]
[2 4 6]
[ 6  4  2  9 22 22 22  3  1]


In [ ]:
# 2D NumPy Array Slicing
# array[row_start:row_stop:row_step, col_start:col_stop:col_step]

import numpy as np

# create a 2D array 
array1 = np.array([[1, 3, 5, 7], 
                      [9, 11, 13, 15],
                      [2, 4, 6, 8]])


# slice the array to get the first two rows and columns
subarray1 = array1[:2, :2]

# slice the array to get the last two rows and columns
subarray2 = array1[1:3, 2:4]

# print the subarrays
print("First Two Rows and Columns: \n",subarray1)
print("Last two Rows and Columns: \n",subarray2)

## NumPy Array Reshaping
NumPy array reshaping simply means changing the shape of an array without changing its data.

In [ ]:
# Reshape 1D Array to 2D Array in NumPy

import numpy as np

array1 = np.array([1, 3, 5, 7, 2, 4, 6, 8])

# reshape a 1D array into a 2D array 
# with 2 rows and 4 columns
result = np.reshape(array1, (2, 4))
print(result)

# For example, reshaping an 8 element 1D array into a 2D array of 2 rows and 4 columns is possible, but reshaping 
# it into a 2D array of 3 rows and 3 columns is not possible as that would require 3x3 = 9 elements.

In [ ]:
# For example, reshaping an 8 element 1D array into a 2D array of 2 rows and 4 columns is possible, but reshaping it into a
# 2D array of 3 rows and 3 columns is not possible as that would require 3x3 = 9 elements.
import numpy as np

# create a 1D array
array1 = np.array([1, 3, 5, 7, 2, 4, 6, 8])

# reshape the 1D array to a 3D array
result = np.reshape(array1, (2, 2, 2))

# print the new array
print("1D to 3D Array: \n",result)

# Flatten N-d Array to 1-D Array Using reshape()
import numpy as np

# flatten 2D array to 1D
array1 = np.array([[1, 3], [5, 7], [9, 11]])
result1 = np.reshape(array1, -1)
print("Flattened 2D array:", result1)

# flatten 3D array to 1D
array2 = np.array([[[1, 3], [5, 7]], [[2, 4], [6, 8]]])
result2 = np.reshape(array2, -1)
print("Flattened 3D array:", result2)

# NumPy Arithmetic Array Operations

NumPy provides a wide range of operations that can perform on arrays, including arithmetic operations.
<!-- NumPy Array Element-Wise Addition -->


In [ ]:
import numpy as np

first_array = np.array([1, 3, 5, 7])
second_array = np.array([2, 4, 6, 8])

# using the + operator
result1 = first_array + second_array
print("Using the + operator:",result1) 

# using the add() function
result2 = np.add(first_array, second_array)
print("Using the add() function:",result2) 
result1 = first_array - second_array
result1 = first_array * second_array
result1 = first_array / second_array

result1 = array1 ** 2
result1 = first_array % second_array

Array Operations	Functions

Array Creation Functions	np.array(), np.zeros(), np.ones(), np.empty(), etc.

Array Manipulation Functions	np.reshape(), np.transpose(), etc.

Array Mathematical Functions	np.add(), np.subtract(), np.sqrt(), np.power(), etc.

Array Statistical Functions	np.median(), np.mean(), np.std(), and np.var().

### Numpy Comparison/Logical Operations

NumPy's comparison operators allow for element-wise comparison of two arrays.

Similarly, logical operators perform boolean algebra, which is a branch of algebra that deals with True and False statements.

In [13]:
# less than operator
result1 = array1 < array2
print("array1 < array2:",result1)    # Output: [ True False False]



ValueError: operands could not be broadcast together with shapes (2,3,4) (5,) 

median()	return the median of an array  

mean()	return the mean of an array

std()	return the standard deviation of an array

percentile()	return the nth percentile of elements in an array

min()	return the minimum element of an array

max()	return the maximum element of an array

In [2]:
import numpy as np

# create a 2D array
array1 = np.array([[2, 4, 6], 
                   [8, 10, 12], 
                   [14, 16, 18]])

# compute median along horizontal axis 
result1 = np.median(array1, axis=1)

print("Median along horizontal axis :", result1)

# compute median along vertical axis
result2 = np.median(array1, axis=0)

print("Median along vertical axis:", result2)

# compute median of entire array
result3 = np.median(array1)

print("Median of entire array:", result3)



# create an array
array1 = np.array([1, 3, 5, 7, 9, 11, 13, 15, 17, 19])

# compute the 25th percentile of the array
result1 = np.percentile(array1, 25)
print("25th percentile:",result1)

# compute the 75th percentile of the array
result2 = np.percentile(array1, 75)
print("75th percentile:",result2)

Median along horizontal axis : [ 4. 10. 16.]
Median along vertical axis: [ 8. 10. 12.]
Median of entire array: 10.0
25th percentile: 5.5
75th percentile: 14.5


## NumPy String Functions

 we can add two strings, change the contents of a string, case conversion, padding, trimming,

In [14]:
import numpy as np

array1 = np.array(['iPhone: ', 'price: '])
array2 = np.array(['15', '$900'])

# perform element-wise array string concatenation
result = np.char.add(array1, array2)

print(result)

import numpy as np  

# define array with three string elements
array1 = np.array(['A', 'B', 'C']) 

#  repeat each element in array1 two times 
result = np.char.multiply(array1, 2)  

print(result)  

# Output: ['AA' 'BB' 'CC']

import numpy as np  

# define an array with three string elements
array1 = np.array(['eric', 'paul', 'sean'])  

# capitalize the first letter of each string in array1 
result = np.char.capitalize(array1)  

print(result) 

# Output: ['Eric' 'Paul' 'Sean']

import numpy as np

array1 = np.array(['nEpalI', 'AmeriCAN', 'CaNadIan'])

# convert all string elements to uppercase
result1 = np.char.upper(array1)

# convert all string elements to lowercase
result2 = np.char.lower(array1)

print("To Uppercase: ",result1)
print("To Lowercase: ",result2)

import numpy as np

# create an array of strings
array1 = np.array(['hello', 'world'])

# join the strings in the array using a dash as the delimiter
result = np.char.join('-', array1)

print(result)

# Output: ['h-e-l-l-o' 'w-o-r-l-d']

import numpy as np

# create two arrays of strings
array1 = np.array(['C', 'Python', 'Swift'])
array2 = np.array(['C++', 'Python', 'Java'])

# check if each element of the arrays is equal
result = np.char.equal(array1, array2)

print(result)

# Output: [False True False]

['iPhone: 15' 'price: $900']
['AA' 'BB' 'CC']
['Eric' 'Paul' 'Sean']
To Uppercase:  ['NEPALI' 'AMERICAN' 'CANADIAN']
To Lowercase:  ['nepali' 'american' 'canadian']
['h-e-l-l-o' 'w-o-r-l-d']
[False  True False]


### Numpy Broadcasting

In NumPy, we can perform mathematical operations on arrays of different shapes. An array with a smaller shape is expanded to match the shape of a larger one. This is called broadcasting.

In [ ]:
import numpy as np

# create 1-D array
array1 = np.array([1, 2, 3])

# create 2-D array
array2 = np.array([[1], [2], [3]])

# add arrays of different dimension
# size of array1 expands to match with array2
sum = array1 + array2

print(sum)

### Broadcasting in NumPy: A Detailed Explanation

**Broadcasting** is a powerful feature in NumPy that allows you to perform arithmetic operations on arrays of different shapes. Instead of reshaping arrays manually to make their shapes compatible, NumPy automatically stretches or "broadcasts" the smaller array across the larger array without copying the data. This makes operations both memory-efficient and faster.

### How Broadcasting Works

For broadcasting to occur, the dimensions of the arrays must be compatible. NumPy compares the shapes of the arrays element-wise, starting from the rightmost dimension, and applies the following rules:

1. **If the dimensions are equal**, the arrays are compatible along that dimension.
2. **If one of the dimensions is 1**, the array with that dimension is stretched to match the size of the other array.
3. **If the dimensions are not equal and neither is 1**, the arrays are incompatible, and broadcasting will fail, raising a `ValueError`.

### Example 1: Basic Broadcasting

Consider two arrays, `A` and `B`:

```python
import numpy as np

A = np.array([1, 2, 3])       # Shape (3,)
B = np.array([[1], [2], [3]]) # Shape (3, 1)
```

- `A` has shape `(3,)`
- `B` has shape `(3, 1)`

When you add `A` and `B`, NumPy will broadcast `A` to shape `(3, 3)` by stretching it:

```python
C = A + B
```

Result:
```python
array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])
```

Here’s how it works:
- `A` (shape `(3,)`) is stretched to shape `(1, 3)`.
- `B` (shape `(3, 1)`) is stretched to shape `(3, 3)`.

Then, the addition is performed element-wise.

### Example 2: Broadcasting with Scalar Values

If you perform an operation between an array and a scalar, NumPy will broadcast the scalar to the shape of the array:

```python
A = np.array([1, 2, 3])
B = 2

C = A * B
```

Result:
```python
array([2, 4, 6])
```

Here, `B` is treated as if it were an array `np.array([2, 2, 2])`, and then multiplied with `A`.

### Example 3: Incompatible Shapes

Consider the following arrays:

```python
A = np.array([1, 2, 3])    # Shape (3,)
B = np.array([1, 2])       # Shape (2,)
```

Attempting to add `A` and `B` will raise a `ValueError` because the shapes `(3,)` and `(2,)` are incompatible:

```python
C = A + B  # Raises ValueError
```

### General Broadcasting Rules

1. **Align shapes from the right**: Start comparing dimensions from the rightmost one.
2. **Broadcast the smaller array**: If one dimension of the smaller array is 1 (or it doesn’t exist), NumPy will broadcast this dimension to match the larger array’s dimension.
3. **Incompatible dimensions raise an error**: If a dimension mismatch occurs and neither dimension is 1, broadcasting fails.

### Example 4: More Complex Broadcasting

```python
A = np.array([[1, 2, 3], [4, 5, 6]])  # Shape (2, 3)
B = np.array([10, 20, 30])            # Shape (3,)
```

Broadcasting `B` to match `A`:

- `B` is broadcast to shape `(2, 3)`, and the operation is performed element-wise.

```python
C = A + B
```

Result:
```python
array([[11, 22, 33],
       [14, 25, 36]])
```

### Benefits of Broadcasting

1. **Memory Efficiency**: No need to create large intermediate arrays.
2. **Simpler Code**: Operations between differently shaped arrays are concise and readable.
3. **Performance**: Broadcasting is optimized in NumPy for speed.

### Summary

Broadcasting in NumPy is a mechanism that allows arrays of different shapes to be used together in arithmetic operations by automatically stretching the smaller array across the larger array without making unnecessary copies. This feature makes array operations in NumPy powerful, memory-efficient, and fast. However, it's essential to understand the rules of broadcasting to avoid shape-related errors during operations.

In [ ]:
# Unary operators:


### NumPy Matrices: A Comprehensive Guide with Examples

NumPy, short for Numerical Python, is a powerful library in Python used for numerical computations. It provides a versatile and efficient way to handle large multidimensional arrays and matrices. While NumPy arrays are more general-purpose and can have any number of dimensions, NumPy also has a specialized matrix class, `numpy.matrix`, which is strictly 2-dimensional. However, using `numpy.matrix` is less common nowadays; most users work with `numpy.array` due to its greater flexibility.

Here, we will explore various operations and concepts related to matrices in NumPy, using `numpy.array` as the standard approach.

### 1. **Creating Matrices**

Matrices in NumPy can be created using the `numpy.array()` function by passing a list of lists:

```python
import numpy as np

# Creating a 2x3 matrix
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("Matrix:\n", matrix)
```

Output:
```python
Matrix:
 [[1 2 3]
 [4 5 6]]
```

### 2. **Matrix Properties**

You can easily inspect the properties of a matrix:

```python
# Shape of the matrix (rows, columns)
print("Shape:", matrix.shape)

# Number of elements (rows * columns)
print("Size:", matrix.size)

# Number of dimensions (for a matrix, this is always 2)
print("Number of dimensions:", matrix.ndim)
```

Output:
```python
Shape: (2, 3)
Size: 6
Number of dimensions: 2
```

### 3. **Matrix Indexing and Slicing**

You can access elements of a matrix using indexing and slicing:

```python
# Accessing a single element
element = matrix[0, 1]
print("Element at row 0, column 1:", element)

# Slicing: Extracting a submatrix
submatrix = matrix[:, 1:]
print("Submatrix with all rows and columns 1 onwards:\n", submatrix)
```

Output:
```python
Element at row 0, column 1: 2
Submatrix with all rows and columns 1 onwards:
 [[2 3]
 [5 6]]
```

### 4. **Basic Matrix Operations**

#### a. **Addition and Subtraction**

Matrices of the same shape can be added or subtracted element-wise:

```python
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8, 9], [10, 11, 12]])

# Matrix addition
C = A + B
print("Matrix Addition:\n", C)

# Matrix subtraction
D = A - B
print("Matrix Subtraction:\n", D)
```

Output:
```python
Matrix Addition:
 [[ 8 10 12]
 [14 16 18]]

Matrix Subtraction:
 [[-6 -6 -6]
 [-6 -6 -6]]
```

#### b. **Element-wise Multiplication**

This operation multiplies corresponding elements of two matrices:

```python
E = A * B
print("Element-wise Multiplication:\n", E)
```

Output:
```python
Element-wise Multiplication:
 [[ 7 16 27]
 [40 55 72]]
```

#### c. **Matrix Multiplication (Dot Product)**

For matrix multiplication, you use either the `np.dot()` function or the `@` operator:

```python
# Matrix multiplication
F = np.dot(A, B.T)  # Transpose B to make it compatible for multiplication
print("Matrix Multiplication:\n", F)

# Alternatively
G = A @ B.T
print("Matrix Multiplication using @:\n", G)
```

Output:
```python
Matrix Multiplication:
 [[ 50  68]
 [122 167]]

Matrix Multiplication using @:
 [[ 50  68]
 [122 167]]
```

### 5. **Matrix Transpose**

The transpose of a matrix flips it over its diagonal:

```python
H = A.T
print("Transpose of Matrix A:\n", H)
```

Output:
```python
Transpose of Matrix A:
 [[1 4]
 [2 5]
 [3 6]]
```

### 6. **Matrix Inversion**

Inverting a matrix is possible only if the matrix is square (same number of rows and columns) and non-singular (determinant is not zero):

```python
# Creating a square matrix
I = np.array([[1, 2], [3, 4]])

# Inverse of the matrix
I_inv = np.linalg.inv(I)
print("Inverse of Matrix I:\n", I_inv)
```

Output:
```python
Inverse of Matrix I:
 [[-2.   1. ]
 [ 1.5 -0.5]]
```

### 7. **Matrix Determinant**

The determinant is a scalar value that can be computed from the elements of a square matrix:

```python
det_I = np.linalg.det(I)
print("Determinant of Matrix I:", det_I)
```

Output:
```python
Determinant of Matrix I: -2.0000000000000004
```

### 8. **Eigenvalues and Eigenvectors**

Eigenvalues and eigenvectors are important concepts in linear algebra, often used in matrix decompositions:

```python
eigenvalues, eigenvectors = np.linalg.eig(I)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)
```

Output:
```python
Eigenvalues: [-0.37228132  5.37228132]
Eigenvectors:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
```

### 9. **Solving Linear Systems**

If you have a system of linear equations represented as \(Ax = b\), you can solve for \(x\) using:

```python
b = np.array([5, 6])
x = np.linalg.solve(I, b)
print("Solution of linear system (x):", x)
```

Output:
```python
Solution of linear system (x): [-4.   4.5]
```

### 10. **Matrix Rank**

The rank of a matrix is the dimension of the vector space generated by its columns. It tells you how many columns are linearly independent:

```python
rank_I = np.linalg.matrix_rank(I)
print("Rank of Matrix I:", rank_I)
```

Output:
```python
Rank of Matrix I: 2
```

### 11. **Matrix Power**

To raise a square matrix to a specific power, use `np.linalg.matrix_power()`:

```python
J = np.linalg.matrix_power(I, 2)
print("Matrix I raised to power 2:\n", J)
```

Output:
```python
Matrix I raised to power 2:
 [[ 7 10]
 [15 22]]
```

### 12. **Singular Value Decomposition (SVD)**

SVD is a method of decomposing a matrix into three other matrices:

```python
U, S, V = np.linalg.svd(A)
print("U Matrix:\n", U)
print("Singular Values:", S)
print("V Matrix:\n", V)
```

Output:
```python
U Matrix:
 [[-0.3863177  -0.92236578]
 [-0.92236578  0.3863177 ]]
Singular Values: [9.508032   0.77286964]
V Matrix:
 [[-0.42866713 -0.56630692 -0.7039467 ]
 [ 0.80596391  0.11238241 -0.58119911]
 [-0.40824829  0.81649658 -0.40824829]]
```

### Summary

NumPy's matrix operations are essential for a wide range of scientific and engineering applications. Here are the key points:

- **Matrix Creation**: Use `np.array()` to create matrices.
- **Basic Operations**: Perform addition, subtraction, multiplication, and transposition.
- **Advanced Operations**: Calculate determinants, inverses, eigenvalues, and solve linear systems.
- **Decompositions**: Singular Value Decomposition (SVD) and other matrix factorizations are critical in data analysis and machine learning.

By mastering these operations, you can efficiently handle matrix computations in your Python programs.

Matrices and their operations are fundamental in many areas of science, engineering, and computer science. NumPy, with its efficient handling of matrices, is widely used in various real-world applications. Let’s explore the importance of matrices, the use cases, and real-world examples, along with explanations of where and how these operations are utilized.

### **Why Use Matrices?**

1. **Mathematical Modeling**: Many problems in physics, economics, engineering, and computer science are naturally represented as systems of linear equations, which are best solved using matrices.

2. **Data Representation**: In data science, matrices are used to represent datasets where rows often represent samples and columns represent features.

3. **Graphics and Image Processing**: Images are represented as matrices of pixel values, and various transformations (like rotation, scaling) are done using matrix operations.

4. **Machine Learning**: Matrices are crucial in machine learning algorithms, especially for operations like linear regression, neural networks, and principal component analysis.

### **Use Cases and Real-World Examples**

#### **1. Linear Algebra in Physics and Engineering**

- **Use Case**: Solving systems of linear equations.
- **Example**: In physics, when analyzing electrical circuits or mechanical structures, the relationships between forces, currents, or other quantities can be modeled as a system of linear equations. Solving these systems often requires matrix operations like inversion or multiplication.

- **Explanation**: Consider a scenario where you need to solve a circuit with multiple loops. Each loop's equation can be represented in matrix form, and using matrix operations like inversion, you can solve for the current or voltage at different points in the circuit.

    ```python
    import numpy as np
    
    # Example of a system of linear equations: Ax = b
    A = np.array([[3, 2], [1, 2]])
    b = np.array([8, 7])
    
    # Solve for x
    x = np.linalg.solve(A, b)
    print("Solution:", x)
    ```

- **Real-World**: Engineers use these techniques to design circuits and analyze mechanical systems, ensuring they function correctly under different conditions.

#### **2. Data Science and Machine Learning**

- **Use Case**: Data representation and algorithm implementation.
- **Example**: In machine learning, data is often represented as a matrix where rows represent individual data points and columns represent features. Operations like matrix multiplication are used in training algorithms.

- **Explanation**: In a simple linear regression model, you want to predict an output variable (Y) from one or more input variables (X). The relationship between X and Y can be modeled as \( Y = XW + b \), where W is a weight matrix, and b is a bias term. The process of finding the optimal W is done through matrix operations.

    ```python
    X = np.array([[1, 2], [3, 4], [5, 6]])
    W = np.array([[0.5], [1]])
    b = np.array([1])
    
    # Predict Y
    Y_pred = X @ W + b
    print("Predicted Y:", Y_pred)
    ```

- **Real-World**: Companies like Netflix use matrix operations to recommend movies by analyzing user preferences, which are represented in large matrices.

#### **3. Image Processing**

- **Use Case**: Transforming and analyzing images.
- **Example**: Images are essentially matrices where each element represents a pixel’s color intensity. Operations like blurring, edge detection, and transformation (rotation, scaling) are performed using matrix operations.

- **Explanation**: Consider image rotation. You can rotate an image by multiplying its pixel matrix by a rotation matrix. This is crucial in applications like photo editing software.

    ```python
    from scipy.ndimage import rotate
    import numpy as np
    
    # Sample image matrix (grayscale)
    image = np.array([[0, 255, 0], [255, 0, 255], [0, 255, 0]])
    
    # Rotate the image by 45 degrees
    rotated_image = rotate(image, 45)
    print("Rotated Image Matrix:\n", rotated_image)
    ```

- **Real-World**: In medical imaging, MRI and CT scans are processed using matrix operations to create clear images from raw data.

#### **4. Network Analysis**

- **Use Case**: Analyzing connections and flows in networks.
- **Example**: Social networks can be represented as matrices where each element indicates the connection strength between users. Operations like matrix multiplication can help analyze the spread of information or detect communities.

- **Explanation**: The adjacency matrix of a graph represents the connections between nodes (e.g., people in a social network). By raising this matrix to a power, you can determine the number of paths between nodes.

    ```python
    # Adjacency matrix of a simple graph
    adjacency_matrix = np.array([[0, 1, 0], [1, 0, 1], [0, 1, 0]])
    
    # Calculate paths of length 2
    paths_length_2 = np.linalg.matrix_power(adjacency_matrix, 2)
    print("Paths of length 2:\n", paths_length_2)
    ```

- **Real-World**: Companies like Facebook analyze social networks to improve friend suggestions and targeted advertisements.

#### **5. Robotics and Control Systems**

- **Use Case**: Transforming and controlling motion.
- **Example**: In robotics, matrices are used to model and control the motion of robotic arms. Transformations like rotation, scaling, and translation are essential to position and orient the robot correctly.

- **Explanation**: A robot arm’s position can be described using a transformation matrix. By multiplying matrices that represent different movements (e.g., rotations around different axes), you can compute the final position of the arm.

    ```python
    # Example of a rotation matrix in 2D
    theta = np.pi / 4  # 45 degrees
    rotation_matrix = np.array([[np.cos(theta), -np.sin(theta)], 
                                [np.sin(theta), np.cos(theta)]])
    
    # Initial position
    position = np.array([1, 0])
    
    # New position after rotation
    new_position = rotation_matrix @ position
    print("New Position:", new_position)
    ```

- **Real-World**: In autonomous vehicles, matrix operations are used to interpret sensor data and make real-time decisions about navigation.

### **Conclusion**

Matrices are ubiquitous in technical fields because they allow complex systems and data to be represented and manipulated efficiently. By understanding and applying matrix operations, you can tackle a wide range of problems in various disciplines, from engineering to data science and beyond. NumPy, with its powerful matrix handling capabilities, is an essential tool for implementing these operations effectively in Python.

Matrices play a crucial role in data science, especially in areas such as machine learning, data manipulation, and statistical analysis. Here are some common use cases where matrices are used in data science:

### 1. **Data Representation:**

In data science, datasets are often represented as matrices where:
- **Rows** represent individual data points (e.g., records, samples).
- **Columns** represent features or variables (e.g., age, height, income).

**Example:**
A dataset of house prices might have columns for the number of bedrooms, size in square feet, and price. This data can be represented as a matrix:

\[
\text{Dataset} = \begin{pmatrix}
3 & 1500 & 300000 \\
2 & 1200 & 250000 \\
4 & 1800 & 350000 \\
\end{pmatrix}
\]

### 2. **Linear Regression:**

Linear regression is a fundamental machine learning algorithm that models the relationship between a dependent variable and one or more independent variables using a linear equation.

- The input data (features) can be represented as a matrix `X`.
- The coefficients (weights) can be represented as a vector `β`.
- The output (predicted values) can be represented as a vector `Y`.

The linear regression model can be expressed as:

\[
Y = X \times β
\]

Where:
- `X` is the matrix of input features.
- `β` is the vector of coefficients.
- `Y` is the vector of predicted values.

**Example:**

```python
import numpy as np

# Features (X): matrix with 3 rows (samples) and 2 columns (features)
X = np.array([[1, 1500],
              [1, 1200],
              [1, 1800]])

# Coefficients (β): vector
β = np.array([50000, 200])

# Predicted Prices (Y): matrix multiplication
Y = np.dot(X, β)

print("Predicted Prices:", Y)
```

### 3. **Principal Component Analysis (PCA):**

PCA is a dimensionality reduction technique used to reduce the number of variables in a dataset while retaining most of the original variance. The data is first centered and then transformed using matrix operations (e.g., eigenvectors and eigenvalues).

- **Covariance Matrix:** A matrix that captures the variance and covariance of the features in the dataset.
- **Eigenvectors and Eigenvalues:** Calculated from the covariance matrix to identify the principal components.

**Example:**
PCA reduces a dataset with many features to a smaller set of uncorrelated features (principal components).

### 4. **Neural Networks:**

In deep learning, neural networks are trained using matrices to represent the inputs, weights, and outputs of each layer.

- **Input Layer:** The input data is represented as a matrix.
- **Weights:** The connections between layers are represented as matrices.
- **Output Layer:** The output predictions are the result of matrix multiplications and activations.

**Example:**
The forward propagation step in a neural network can be represented using matrix multiplication.

### 5. **Image Processing:**

In image processing, images are represented as matrices where each pixel's intensity is an element in the matrix.

- **Grayscale Image:** A 2D matrix where each element represents the intensity of a pixel.
- **Color Image:** A 3D matrix where each channel (Red, Green, Blue) is a 2D matrix.

**Example:**
Image filters (e.g., blurring, sharpening) are applied using matrix operations like convolution.

### 6. **Collaborative Filtering in Recommender Systems:**

Matrices are used in collaborative filtering to recommend items to users based on past interactions. The interaction between users and items (e.g., ratings) is represented as a matrix.

- **User-Item Matrix:** Rows represent users, columns represent items, and the elements represent the user's rating for an item.
- **Matrix Factorization:** Techniques like Singular Value Decomposition (SVD) are used to factorize the user-item matrix to predict missing ratings.

**Example:**
Predicting a user’s rating for a movie they haven’t watched based on similar users’ ratings.

### Summary:

Matrices are a fundamental tool in data science, enabling efficient computation, data representation, and algorithm implementation. They are essential for handling large datasets, performing linear algebra operations, and implementing machine learning algorithms.

## 3D array

A **3D array** is an array of arrays of arrays, meaning it has three dimensions or axes. You can think of a 3D array as a stack of 2D matrices, where each matrix is layered on top of another.

### Structure of a 3D Array:

1. **First Dimension:** Represents the number of 2D matrices.
2. **Second Dimension:** Represents the number of rows in each 2D matrix.
3. **Third Dimension:** Represents the number of columns in each 2D matrix.

### Example of a 3D Array:

Consider a 3D array with shape `(2, 3, 4)`, which means:
- There are `2` matrices (layers).
- Each matrix has `3` rows.
- Each row has `4` columns.

Visually, this 3D array can be represented as:

\[
\text{3D Array} = \left[
\begin{pmatrix}
1 & 2 & 3 & 4 \\
5 & 6 & 7 & 8 \\
9 & 10 & 11 & 12
\end{pmatrix},
\begin{pmatrix}
13 & 14 & 15 & 16 \\
17 & 18 & 19 & 20 \\
21 & 22 & 23 & 24
\end{pmatrix}
\right]
\]

### Working with 3D Arrays in NumPy:

You can create and manipulate 3D arrays using NumPy:

```python
import numpy as np

# Create a 3D array
arr_3d = np.array([[[1, 2, 3, 4],
                    [5, 6, 7, 8],
                    [9, 10, 11, 12]],
                   
                   [[13, 14, 15, 16],
                    [17, 18, 19, 20],
                    [21, 22, 23, 24]]])

print("3D Array:")
print(arr_3d)
print("\nShape of the array:", arr_3d.shape)
print("Number of dimensions:", arr_3d.ndim)
```

### Output:

```
3D Array:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]

Shape of the array: (2, 3, 4)
Number of dimensions: 3
```

### Explanation:

- **Shape:** `(2, 3, 4)` indicates:
  - 2 layers (or 2 matrices),
  - Each with 3 rows,
  - Each row with 4 columns.
- **Dimensions:** The array has 3 dimensions.

### Use Cases of 3D Arrays:

1. **Image Processing:**
   - A color image is often represented as a 3D array:
     - The first dimension represents the height (rows) of the image.
     - The second dimension represents the width (columns) of the image.
     - The third dimension represents the color channels (Red, Green, Blue).

2. **Video Data:**
   - A video can be represented as a sequence of frames (images), where each frame is a 2D array. A video with multiple frames can be stored in a 3D array:
     - The first dimension represents time (frame number).
     - The second and third dimensions represent the height and width of each frame.

3. **Scientific Data:**
   - In fields like physics and meteorology, 3D arrays can represent data in three spatial dimensions, such as temperature readings across a 3D grid of locations.

4. **Neural Networks:**
   - In deep learning, especially in convolutional neural networks (CNNs), 3D arrays are used to represent batches of images or feature maps.

### Summary:

A 3D array is a multi-dimensional array with three axes, used to represent complex data structures like stacked matrices, video frames, or multi-channel images. They are essential in various fields such as image processing, scientific computing, and machine learning.

In [2]:
import numpy as np

# Features (X): matrix with 3 rows (samples) and 2 columns (features)
X = np.array([[1, 1500],
              [3, 1200],
              [1, 1800]])

# Coefficients (β): vector
β = np.array([50000, 200])

# Predicted Prices (Y): matrix multiplication
Y = np.dot(X, β)

print("Predicted Prices:", Y)

Predicted Prices: [350000 390000 410000]


In [ ]:
import numpy as np

# Coefficient matrix A
A = np.array([[2, 3, 1],
              [4, 1, 2],
              [3, 2, 3]])

# Right-hand side vector b
b = np.array([1, 2, 3])

# Solve the system of equations
solution = np.linalg.solve(A, b)

# Extract the values of x, y, z
x, y, z = solution

print(f"Solution: x = {x}, y = {y}, z = {z}")


In [4]:
import numpy as np

# Create two arrays
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([1, 3, 2, 4, 5])

# 1. np.equal(): Compare if two arrays have the same elements
equal_result = np.equal(arr1, arr2)
print("Equal comparison:", equal_result)
# Output: [ True False False  True  True ]
# Explanation: Elements at positions 0, 3, and 4 are equal between the two arrays.

# 2. np.not_equal(): Compare if two arrays have different elements
not_equal_result = np.not_equal(arr1, arr2)
print("Not equal comparison:", not_equal_result)
# Output: [False  True  True False False]
# Explanation: Elements at positions 1 and 2 are not equal between the two arrays.

# 3. np.logical_and(): Perform element-wise logical AND operation
logical_and_result = np.logical_and(arr1 > 2, arr2 > 2)
print("Logical AND result:", logical_and_result)
# Output: [False False  True  True  True]
# Explanation: Both arr1 and arr2 must have elements greater than 2 for the result to be True.

# 4. np.logical_or(): Perform element-wise logical OR operation
logical_or_result = np.logical_or(arr1 > 2, arr2 > 2)
print("Logical OR result:", logical_or_result)
# Output: [False  True  True  True  True]
# Explanation: If either arr1 or arr2 have elements greater than 2, the result is True.

# 5. np.logical_not(): Perform element-wise logical NOT operation
logical_not_result = np.logical_not(arr1 > 3)
print("Logical NOT result:", logical_not_result)
# Output: [ True  True  True False False]
# Explanation: Elements where arr1 > 3 are False, and others are True.


Equal comparison: [ True False False  True  True]
Not equal comparison: [False  True  True False False]
Logical AND result: [False False False  True  True]
Logical OR result: [False  True  True  True  True]
Logical NOT result: [ True  True  True False False]
