In [ ]:
# install
!pip install numpy 

In [ ]:
import numpy as np #2005 by Travis Oliphant 

In [ ]:
import numpy as np #2005 by Travis Oliphant  print(np.__doc__)
# check the version
np.__version__

In [ ]:
data= [1, 2, 3, 4, 5] # list create 
print(data)
print(type(data))

In [ ]:
# create numpy array from list
arr = np.array(data)
arr

In [ ]:
type(arr)

An array is a data structure that stores a collection of elements, typically of the same data type, in a contiguous block of memory. Arrays allow you to store multiple values in a single variable and access these values using indices. In most programming languages, including Python (via NumPy), arrays are used for efficiently storing and manipulating numerical data.

### Characteristics of Arrays:
1. **Fixed Size:**
   - Once an array is created, its size is fixed, meaning it cannot grow or shrink dynamically like Python lists. The number of elements (length) in an array is set at the time of its creation.

2. **Homogeneous Elements:**
   - All elements in an array must be of the same data type (e.g., all integers, all floats, etc.). This makes operations on arrays more efficient.

3. **Contiguous Memory Allocation:**
   - Elements in an array are stored in contiguous memory locations, which allows for fast access and efficient memory use.

4. **Indexing:**
   - Arrays use zero-based indexing, meaning the first element is accessed with index 0, the second with index 1, and so on. This allows for direct access to any element in constant time (O(1)).

5. **Efficient Computation:**
   - Due to the fixed size and contiguous memory allocation, arrays allow for efficient computation, particularly in numerical operations where large datasets are involved.


In [ ]:
arr

In [ ]:
[1, 2, 3, 4, 5, "sha"]

In [ ]:
data = [1, 2, 3, 4, 5, "sha"] #homogeneous data type -- all string
arr1 = np.array(data)
arr1

In [ ]:
type(arr) #object type

In [ ]:
arr1.dtype #data type of array elements

In [ ]:
# check the dimensions
arr1.ndim

In [ ]:
# shape of the array
arr.shape

In [ ]:
# number of elements in the array
arr.size

Array:> An array is a foundational data structure that stores a collection of elements of the same data type in contiguous memory locations.

Numpy Array:> A NumPy array is the primary data structure for scientific computing in Python, providing a high-performance, multidimensional array object called ndarray.

### Types of Arrays:

In [ ]:
# - **Zero-Dimensional Array (0D Array):** scaler
arr_0d = np.array(42)
arr_0d.ndim  # Output: 0

In [ ]:
# 1D Array/ Vector/Series
arr_1d = np.array([1, 2, 3, 4, 5])
print(arr_1d.ndim ) # Output: 1
print(arr.shape)

![](https://cdn-images-1.medium.com/v2/resize:fit:1120/1*Ikn1J6siiiCSk4ivYUhdgw.png)
![](https://i0.wp.com/indianaiproduction.com/wp-content/uploads/2019/06/NumPy-shape.png?resize=1200%2C488&ssl=1)

In [ ]:
# 2D Array/Matrix/table/tabular data/dataframe --> rows and columns
arr_2d = np.array([[1, 2, 3]])
print("number of dimension ",arr_2d.ndim)  # Output: 
print(arr_2d)
print("rows & column",arr_2d.shape)

In [ ]:
# 2D Array/Matrix/table/tabular data/dataframe --> rows and columns
arr_2d = np.array([[1, 2, 3], 
                    [4, 5, 6]
                    ])
arr_2d.ndim  # Output: 
arr_2d

In [ ]:
arr_2d  # Output: (2, 3)

In [ ]:
# 3D Array
arr_3d = np.array([[[1, 2], [3, 4]],
                     [[5, 6], [7, 8]]
                ])
arr_3d

In [ ]:
arr_3d.ndim  # Output: 3
arr_3d.shape  # Output: (2, 2, 2)

In [ ]:
# 3D Array
import numpy as np
arr_3d2 = np.array([
                    [[1, 2, 4], [3, 4, 5]],
                    [[5, 6, 7], [7, 8, 9]]
                    ])
arr_3d2

In [ ]:
arr_3d2.shape

In [ ]:
# create 7D array
arr_7d =np.array([[[[[[[1,2,3],[1,2,3]]]]]]])
print(arr_7d)
print(arr_7d.ndim)
print(arr_7d.shape)

In [ ]:
# create 7D array
arr_7d =np.array([[[[[
                        [[1,2,3],[1,2,3]],
                        [[1,2,3],[1,2,3]],
                        [[1,2,3],[1,2,3]]

                ]]]]])
print(arr_7d)
print(arr_7d.ndim)
print(arr_7d.shape)

In [ ]:
np.array([1, 2, 3, 4, 5,6], dtype=np.float32, ndmin=7)


### Types of Arrays:
- **Zero-Dimensional Array (0D Array):**
- **One-Dimensional Array (1D Array):**
  - A linear array where elements are arranged in a single row.
  - Example: `[1, 2, 3, 4, 5]`

- **Two-Dimensional Array (2D Array):**
  - An array of arrays, often visualized as a matrix with rows and columns.
  - Example: 
    ```
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
    ```

- **Multi-Dimensional Array:**
  - An array with more than two dimensions, such as a 3D array, which can represent a cube of data.
  - Example: A 3x3x3 cube.

### Arrays in NumPy:
In Python, the basic array structure is the list, but for more advanced numerical operations, the NumPy library is commonly used. NumPy arrays (`ndarray`) provide additional functionality and performance benefits over Python lists, making them ideal for scientific computing.

#### Creating Arrays in NumPy:
```python
import numpy as np

# 1D Array
array_1d = np.array([1, 2, 3, 4, 5])

# 2D Array (Matrix)
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# 3D Array
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print("1D Array:\n", array_1d)
print("2D Array:\n", array_2d)
print("3D Array:\n", array_3d)
```

In [ ]:
# Real world example
from PIL import Image
import numpy as np

# Load the image
img = Image.open(r'c:\Users\hp\Documents\ds_materials\5.0_python_6.libraries\python_libraries\1.numpy\class\img.jpeg')

# Convert the image to a NumPy array
img_array = np.asarray(img)

print(type(img_array))
print(img_array.shape) # e.g., (height, width, channels)


In [ ]:
img_array[0].reshape(1, img_array.shape[1], img_array.shape[2])

In [ ]:
p = np.array([[[[[
    [1, 2, 3],[1,2,3],[3,4,5]
 ] ]] ]])

In [ ]:
import matplotlib.pyplot as plt

plt.imshow(img_array[600:1000, 300:800, 2])  # Single channel
plt.show()

In [ ]:
from PIL import Image
import numpy as np

# Assuming 'img_array' is your NumPy array (pixel data must be uint8 type)
# Example: create a simple array with some data
height, width = 100, 100
data = np.zeros((height, width, 3), dtype=np.uint8) 
data[25:75, 25:75] = [255, 0, 0] # Add a red square

# Convert the NumPy array to a PIL Image object
img_from_array = Image.fromarray(data, 'RGB')

# Save the image
img_from_array.save(r'c:\Users\hp\Documents\ds_materials\5.0_python_6.libraries\python_libraries\1.numpy\class\new_image.png')

# Display the image (optional)
# img_from_array.show()


## NumPy Array Indexing



Access 2-D Arrays
Access 3-D Arrays
Negative Indexing

### INdexing and slicing 

In [ ]:
ar1 = np.array([7,6,8,9])
print(ar1)
# get the only 3rd element
print(ar1[2]) # 1D indexing

In [ ]:
# get the from 2to 4 element
print(ar1[1:4]) # 1D slicing 

In [ ]:
arr2d = np.array([[1,2,3],[6,7,8]])
print(arr2d)
# Access 2-D Arrays
# get 3 from arr2d
print(arr2d[0][2]) #2d indexing
# name[row][col]
arr2d[0,2] # name[row, col]

In [ ]:
# get the value 7 ,8
print(arr2d[1][1:3]) # 2D slicing
# row[start:stop:step]
# col[start:stop:step]

In [ ]:
# get the value 3, 8
print(arr2d[0:3 , 2]) # 2D indexing

In [ ]:
arr2d

In [ ]:
arr2d[0, 2] # replace 3 with 9 reassignment


In [ ]:
arr2d[0, 2]=9   # replace 3 with 9 reassignment
arr2d

In [ ]:
arr2d[0:3 , 2]=10,20 # replace 3,8 with 10,20 reassignment
arr2d

In [ ]:
# 3d Slicing and indexing
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr3d)
arr3d.shape

In [ ]:
# get the value 8
arr3d[1, 0, 1]

In [ ]:
#Q. slice the value 7 and 8 from array
arr3d[1, 0, 0:2]
# 4 and 10
arr3d[0:2, 1, 0]

 # [ 7  8 ]
#   [10 11]
arr3d[1, :, 0:2]

#### datatype change

In [ ]:
arr7 = np.array(['2',6,7,8])
arr7

In [ ]:
# astype --> use to change the datatype of array
arr7 = arr7.astype('int16')
arr7

## There are multiple ways to generating arrays

In [ ]:
import numpy as np
# 1.np.array  method
arr =np.array([3,4,5,6,7],dtype="float",ndmin=2)
arr

In [ ]:
# 2. np.zeros --> create a  array with only  0 s
zeros = np.zeros((3, 4))  # 3 rows and 4 columns
zeros

In [ ]:
# 3. np.ones --> create a  array with only  1 s
ones = np.ones((3,4))
ones

In [ ]:
# 4, full --> create a  array with only  any number s
full = np.full((3,4),3)
full

In [ ]:
# empty use for random data for 1 time generate
np.empty((3,4))

In [ ]:
# 5. arange generate values in a range
arr_range = np.arange(1, 10,2)  # start, stop, step
arr_range

In [ ]:
# 6. np.linspace(start, stop , number of element) With equally spaced values
ls = np.linspace(0,1, 5)
ls

In [ ]:
np.linspace(0,10, 20)

In [ ]:
# 7. With random values--> values between 0 and 1
arr_random = np.random.rand(3, 2)  # 3 rows and 2 columns with values between 0 and 1
arr_random

In [ ]:
# 8. int With random values
arr_random2 = np.random.randint(1,20,6)  #return integer number randint(start, end, number of elements)
arr_random2

In [ ]:
# 9. With normal random values--> values ---> follow normal distribution
arr_random = np.random.randn(10)  
arr_random

In [ ]:
np.random.seed(34) # random any seed ++use for freeze the random data after 1st time generate
arr_random = np.random.randn(10) 
arr_random

In [ ]:
# pip install matplotlib

In [ ]:
import matplotlib.pyplot as plt
plt.hist(arr_random,bins=10)
plt.show()

##### NumPy Array Reshaping

In [ ]:
import  numpy as np
arr8 = np.arange(0,16)
print(arr8)
# convert  1D to 2d
arr8.reshape((4,4))

In [ ]:
# convert  1D to 2d
arr8.reshape((4,3)) # size  mismach  error 

In [ ]:
arr9 = arr8.reshape((4,4))
arr9

In [ ]:
arr8.reshape((3,3,3)) # multipications of all should be same as size of original array

In [ ]:
# 1d to 3d
arr8.reshape((2,2,4))

 #### unknown dimensions
 multipications of all should be same as size of original array

In [ ]:
arr10 = arr8.reshape((-1,2,2)) # In place of unknown dimensions using -1 
arr10

In [ ]:
arr9.reshape(16)

In [ ]:
arr9.flatten() # change into 1D

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr.reshape(2, 2, -1)
print(newarr)

#### Iterating Arrays

In [ ]:
arr
for i in arr:
    print(i)

In [ ]:
d2 = arr.reshape(2, 4)
for i in d2:
    print(i)
    for  j in i :
        print(j)
    print("=======")

In [ ]:
#  nditer method use for reduce multiple itrations loop
for i in np.nditer(d2):
    print(i)

1
2
3
4
5
6
7
8


arr

In [23]:
arr
d2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [25]:
# Universal Functions (ufuncs)
np.sum(arr)
np.mean(d2) 

np.float64(4.5)

In [27]:
np.mean(d2, axis=0) # column wise mean
np.mean(d2, axis=1) # row wise mean

array([2.5, 6.5])

In [28]:
np.max(d2, axis=1) # row wise mean

array([4, 8])

In [32]:
l1 =[1,2,3]
l2 =[2]
l1+l2

[1, 2, 3, 2]

In [ ]:
arr = np.array([1, 2, 3])
arr+ 2

array([3, 4, 5])

In [37]:
arr = np.array([1, 2, 3])
arr2 = np.array([4, 5,8])
arr+ arr2

array([ 5,  7, 11])

In [40]:
arr = np.array([1, 2, 3,5])
arr2 = np.array([4, 5]).reshape(2,1)
arr+ arr2

array([[ 5,  6,  7,  9],
       [ 6,  7,  8, 10]])


### Operations on Arrays:
- **Element-wise Operations:**
  - You can perform mathematical operations on arrays element-wise.
  ```python
  array = np.array([1, 2, 3, 4])
  result = array + 10  # Adds 10 to each element
  ```

- **Matrix Operations:**
  - Arrays can represent matrices, allowing for operations like matrix multiplication.
  ```python
  matrix1 = np.array([[1, 2], [3, 4]])
  matrix2 = np.array([[5, 6], [7, 8]])
  result = np.dot(matrix1, matrix2)  # Matrix multiplication
  ```

- **Indexing and Slicing:**
  - You can access individual elements or subarrays using indexing and slicing.
  ```python
  array = np.array([1, 2, 3, 4, 5])
  element = array[2]  # Accessing the 3rd element (index 2)
  subarray = array[1:4]  # Slicing from index 1 to 3
  ```


### Use Cases of Arrays:
1. **Data Storage:**
   - Arrays are used to store large datasets, such as time series data, image data, or any numerical data, efficiently in memory.

2. **Mathematical Computations:**
   - Arrays are ideal for performing mathematical computations, such as vector operations, matrix multiplications, and solving systems of equations.

3. **Scientific Simulations:**
   - In scientific research, arrays are used to simulate physical systems, perform numerical analysis, and run experiments with large datasets.

4. **Image Processing:**
   - Images are represented as multi-dimensional arrays (e.g., 2D for grayscale images, 3D for color images), enabling operations like filtering, transformation, and enhancement.

### Conclusion:
Arrays are a fundamental data structure in programming, particularly in numerical computing and data analysis. In Python, while lists can be used as basic arrays, NumPy provides more powerful and efficient array structures (`ndarray`) for handling large datasets and performing complex numerical operations.

# OPTIONAL 
Here's a clear summary of **Linear Algebra functions**, **Concatenation**, and **Splitting** in **NumPy**, along with examples you can use in teaching:

---

### ✅ **Linear Algebra Functions in NumPy (`numpy.linalg`)**

NumPy provides a submodule `numpy.linalg` for linear algebra operations.

#### 1. **Dot Product (Matrix Multiplication)**

```python
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
dot_product = np.dot(A, B)
print(dot_product)
```

#### 2. **Matrix Transpose**

```python
A = np.array([[1, 2], [3, 4]])
transpose = A.T
print(transpose)
```

#### 3. **Matrix Inverse**

```python
A = np.array([[1, 2], [3, 4]])
inverse = np.linalg.inv(A)
print(inverse)
```

#### 4. **Determinant**

```python
A = np.array([[1, 2], [3, 4]])
det = np.linalg.det(A)
print(det)
```

#### 5. **Eigenvalues and Eigenvectors**

```python
A = np.array([[4, -2], [1, 1]])
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)
```

#### 6. **Solving Linear Equations (Ax = b)**

```python
A = np.array([[2, 1], [1, 3]])
b = np.array([8, 13])
x = np.linalg.solve(A, b)
print("Solution x:", x)
```

---

### ✅ **Concatenation in NumPy**

Used to join arrays.

#### 1. **`np.concatenate()`**

```python
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
result = np.concatenate((a, b), axis=0)  # row-wise
print(result)
```

#### 2. **`np.vstack()` — Vertical Stack (rows)**

```python
a = np.array([1, 2])
b = np.array([3, 4])
result = np.vstack((a, b))
print(result)
```

#### 3. **`np.hstack()` — Horizontal Stack (columns)**

```python
a = np.array([1, 2])
b = np.array([3, 4])
result = np.hstack((a, b))
print(result)
```

#### 4. **`np.stack()` — Join with new axis**

```python
a = np.array([1, 2])
b = np.array([3, 4])
result = np.stack((a, b), axis=0)
print(result)
```

---

### ✅ **Splitting Arrays in NumPy**

Used to divide arrays.

#### 1. **`np.split()` — General split**

```python
a = np.array([1, 2, 3, 4, 5, 6])
result = np.split(a, 3)
print(result)  # [array([1,2]), array([3,4]), array([5,6])]
```

#### 2. **`np.vsplit()` — Vertical split**

```python
a = np.array([[1, 2], [3, 4], [5, 6]])
result = np.vsplit(a, 3)
print(result)
```

#### 3. **`np.hsplit()` — Horizontal split**

```python
a = np.array([[1, 2, 3], [4, 5, 6]])
result = np.hsplit(a, 3)
print(result)
```

---

Would you like a printable PDF or slides version for your students?


It looks like you typed **“broadstanding”**, which might be a typo or a misheard term.

Here are a few possible interpretations:

1. **Did you mean “broadcasting” in NumPy?**
   If so, broadcasting is a fundamental concept in NumPy that allows arithmetic operations on arrays of different shapes.

   ---

   ### ✅ **Broadcasting in NumPy**

   Broadcasting automatically expands smaller arrays to match the shape of larger ones in element-wise operations.

   #### Example 1: Add scalar to array

   ```python
   import numpy as np

   a = np.array([1, 2, 3])
   b = 10
   print(a + b)  # Output: [11 12 13]
   ```

   #### Example 2: Add (3,1) array with (1,3) array

   ```python
   a = np.array([[1], [2], [3]])     # shape (3,1)
   b = np.array([[10, 20, 30]])      # shape (1,3)
   result = a + b                    # shape (3,3)
   print(result)
   # Output:
   # [[11 21 31]
   #  [12 22 32]
   #  [13 23 33]]
   ```

   ---

   ### 🧠 **Broadcasting Rules**

   1. If the shapes differ, NumPy pads the smaller shape with 1s on the left.
   2. Two dimensions are compatible when:

      * They are equal, or
      * One of them is 1
   3. The result shape is the maximum of each dimension.

---

If you meant something else by "broadstanding," could you clarify the term?

Great question! Let's cover the **conditions of broadcasting in NumPy** in a clear and simple way.

---

### ✅ **Conditions of Broadcasting in NumPy**

Broadcasting allows NumPy to perform element-wise operations on arrays of **different shapes**, as long as certain **rules** are followed.

---

### 🧩 **Broadcasting Rules**

Suppose we have two arrays: `A` and `B`.

To broadcast them together:

1. **Align the shapes** **from the right** (pad with 1s on the left if needed).
2. **Dimensions are compatible if:**

   * They are equal, or
   * One of them is 1

---

### 🔢 **Example Scenarios**

#### ✅ **Valid Broadcasting**

```python
A.shape = (3, 1)
B.shape = (1, 4)
Result.shape = (3, 4)  # Compatible
```

Why valid?

* 1st dim: 3 vs 1 → OK (1 can be stretched)
* 2nd dim: 1 vs 4 → OK (1 can be stretched)

#### ❌ **Invalid Broadcasting**

```python
A.shape = (2, 3)
B.shape = (3, 2)
```

* 1st dim: 2 vs 3 → Not compatible
* 2nd dim: 3 vs 2 → Not compatible
  → **Error: operands could not be broadcast together**

---

### 📌 **Examples in Code**

#### Example 1: Broadcast scalar to array

```python
import numpy as np
A = np.array([1, 2, 3])
B = 5
print(A + B)  # [6 7 8]
```

#### Example 2: Broadcast 1D to 2D

```python
A = np.array([[1], [2], [3]])  # shape (3, 1)
B = np.array([10, 20, 30])     # shape (3,)
result = A + B                 # shape (3, 3)
print(result)
```

---

### 📌 Tip for Teaching:

When explaining broadcasting to students, show them how NumPy “virtually” expands the smaller array without actually copying data, which makes it memory-efficient.
