## Prepared by Sanasam Ranbir Singh

# Arithmetic Operation on Tensors
---
Tensor can store data with wide ranges of dimensions, starting from scalar (zero dimensional data) to any dimension. Arithmetic operations like plus, minus, multiplication, division can be applied between two tensors. <b>Element-wise operations between tensors will be performed.</b><br>

For example 
<div>
<img src="attachment:image-12.png" width=500 align="left" />
    </div>
<br><br><br><br><br><br><br><br><br><br><br>
Given two tensors $a$ and $b$, for performing an arithmetic operation, the following compatibilities are checked.

> - If the shape of the respective component dimensions of the tensors are same. Then, they are compatible.
> - For the <b>mismatched</b> component dimensions, one of them has <b>shape 1</b>, Then, they are compatible.
> - Otherwise, they are not compatible.

If the dimension and/or shapes of $a$ and $b$ are not same, but compatible. Then apply <b>Broadcast</b> over the lower dimensional tensor.

### Broadcast (Stretch): Replicate the values

The following example shows multiplication of a vector $a = [1,2,3]$ and scalar $b=2$.
<div>
<img src="attachment:image.png" width=500 align="left"/>
</div>
<br><br><br><br><br><br><br><br><br>
<div>
The shape of the tensor $a$ = (3), i.e., dimension=1<br>
The shape of the tensor $b$ = (1), i.e., dimension=1. A scalar can also be consider as a vector of single element.<br>
The Shapes are different i.e., $(3)!= (1)$, but one of the component dimension is 1. So, apply stretching the tensor with dimension 1, i.e., <b> replicate the values of the tensor till the matching shape</b> of the particular component dimension. 

The value of the scalar is replicated till the matching shape. <b> A scalar can always perform arthmetic operations (+,-,*,/) with a vector.</b></div>


The following example shows the case of higher dimension.

<div>
<img src="attachment:image-8.png" width=400 align="left"\>
    </div>
<div>
    <img src="attachment:image-13.png" width=400 align="left" \>
</div>
<br><br><br><br><br><br><br><br><br>
Another Example:
<div>
<img src="attachment:image-9.png"  width=400 align="left"\>
     </div>
     
<div>
     <img src="attachment:image-10.png" width=400 align="left"\>
    </div>
<br><br><br><br><br><br><br><br><br>

<font color=red><b>The following example are not compatitble.</b></font>
<div>
<img src="attachment:image-11.png" width=600 align="left" /></div>


---

In [1]:
import tensorflow as tf

<div class="alert alert-block alert-danger">
    <font size=5><b>Between Two Scalar Tensors</b></font>
</div>
The scalar tensors are always compatible.

In [2]:
x = tf.constant(5)
y = tf.constant(7)
z = x + y
print(z)

tf.Tensor(12, shape=(), dtype=int32)


<div class="alert alert-block alert-danger">
    <font size=5><b>Between Two Vector Tensors</b></font>
</div>
<br>
Given two tensors $x = [1,2,3]$ and $y = [4,5,6]$, $Shape(x)=Shape(y)=> (3)=(3)$. They are compatible.


In [3]:
x = tf.constant([1,2,3])
y = tf.constant([4,5,6])
z = x + y
print(z)

tf.Tensor([5 7 9], shape=(3,), dtype=int32)


<div class="alert alert-block alert-danger">
    <font size=5><b>Between Two Matrix Tensors</b></font>
</div>
<br>
Given the following two tensors $x$ and $y$,
\begin{equation}
x=
\begin{pmatrix}
  1 & 2 & 3\\
  4 & 5 & 6\\
\end{pmatrix}
\end{equation}<br> and<br>
\begin{equation}
y=
\begin{pmatrix}
  7 & 8 & 9\\
  10 & 11 & 12\\
\end{pmatrix}
\end{equation}

$Shape(x)=Shape(y)=> (2,3)=(2,3)$. They are compatible.

In [4]:
x = tf.constant([[1,2,3],[4,5,6]])
print("x: ")
tf.print(x)
y = tf.constant([[4,5,6],[7,8,9]])
print("y: ")
tf.print(y)
y.numpy()
z = x + y
print("z: ")
tf.print(z)

x: 
[[1 2 3]
 [4 5 6]]
y: 
[[4 5 6]
 [7 8 9]]
z: 
[[5 7 9]
 [11 13 15]]


<div class="alert alert-block alert-danger">
    <font size=5><b>Between Sclar and Vector Tensors</b></font>
</div>
<br>
Given a scalar tensor $x = 2 $ and vector tensor $y = [4,5,6]$, $Shape(x)\neq Shape(y)=> ( )\neq(3)$.<br>
Since scalar can also be defined as vector of one element, broadcast can be appled. Hence, they are compatible.
<br>

<div>
<img src="attachment:image.png" width=400 align="left" />
    </div>


In [5]:
y = tf.constant([1,2,3])
x = tf.constant(2)
z = y * x
tf.print(z)

[2 4 6]


<div class="alert alert-block alert-danger">
    <font size=5><b>Between Vector and Matrix Tensors</b></font>
</div>
<br>
Given a tensor $x = [1,2,3]$ and a matrix tensor
\begin{equation}
y=
\begin{pmatrix}
  4 \\
  5 \\
  6\\
\end{pmatrix}
\end{equation}
 $Shape(x)\neq Shape(y)=> (3)\neq(3\times 1)$.<br>
Since one of all the mismatched component dimensions is 1, broadcast can be appled. Hence, they are compatible.
<br><br>
<div>
    <img src="attachment:image-3.png" width=150 align="left" />
    </div>   
<div>
<img src="attachment:image.png" width=300 align="left" />
    </div>

In [6]:
x = tf.constant([1,2,3])
y = tf.constant([[4],[5],[6]])
z = x + y
tf.print(z)

[[5 6 7]
 [6 7 8]
 [7 8 9]]


## Another Example
Given a tensor $x = [1,2,3,4]$ and a matrix tensor
\begin{equation}
y=
\begin{pmatrix}
  4 &6&7&8 \\
  9 &10&11&12\\
\end{pmatrix}
\end{equation}
 $Shape(x)\neq Shape(y)=> (3)\neq(2\times 3)$.<br> That means,
 <div>
    <img src="attachment:image.png" width=150 align="left"/>
    </div>


In [7]:
x = tf.constant([1,2,3,4])
y = tf.constant([[4,6,7,8],[9,10,11,12]])
z = y + x
tf.print(z)

[[5 8 10 12]
 [10 12 14 16]]


<div class="alert alert-block alert-danger">
    <font size=5><b>Incompatible Example</b></font>
</div>
<br>
Given  $x = [1,2,3]$ and $y = [1,2,3,4]$,
 $Shape(x)\neq Shape(y)=> (3)\neq(4)$.<b>Not Compatible</b> <br><br>
 
<div>
<img src="attachment:image.png" width=250 align="left" />
</div>


In [8]:
x = tf.constant([1,2,3])
y = tf.constant([4,5,6,8])
z = x + y
print(z)

InvalidArgumentError: {{function_node __wrapped__AddV2_device_/job:localhost/replica:0/task:0/device:CPU:0}} Incompatible shapes: [3] vs. [4] [Op:AddV2] name: 

### Another example
Given a tensor $x = [1,2,3]$ and a matrix tensor
\begin{equation}
y=
\begin{pmatrix}
  4 &6&7&8 \\
  9 &10&11&12\\
\end{pmatrix}
\end{equation}

<br>
 $Shape(x)\neq Shape(y)=> (3)\neq(2\times 4)$. That means, <br><br>
 <div>
 <img src="attachment:image.png" width=200 align="left"/>
    </div>

In [9]:
x = tf.constant([1,2,3])
y = tf.constant([[4,5,6,8],[9,10,11,12]])
z = x + y
print(z)

InvalidArgumentError: {{function_node __wrapped__AddV2_device_/job:localhost/replica:0/task:0/device:CPU:0}} Incompatible shapes: [3] vs. [2,4] [Op:AddV2] name: 

## Summary
In this lesson, we have learnt 
> - Different arthmetic operations on tensors.
> - Compatibility of two tensors for performing arithmetic operations.
> - Broadcasting values of a tensor.