In [ ]:
import numpy as np
arr = np.ones((3, 4))

In [ ]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
arr + 5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [ ]:
arr*5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [ ]:
np.empty((3, 4))

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [ ]:
np.eye(3, dtype = int) #n*n matrix #tO calculate inverse of matroix

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [ ]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
#optional

import pandas as pd
pd.DataFrame(arr)

0    1    2    3
0  1.0  1.0  1.0  1.0
1  1.0  1.0  1.0  1.0
2  1.0  1.0  1.0  1.0

In [1]:
#extra topics
import random
random.choice((1, 2, 3, 4, 5, 6))

random.choice('Ajay')
random.randrange(1, 10)
random.random() # a random no is generated between o (included), 1 will be excluded

lis = [1, 2, 3, 4, 5]
random.shuffle(lis)

random.uniform(7, 14) #a no between 7 and 14

7.149147899375323

In [2]:
np.array([])

NameError: name 'np' is not defined

In [ ]:
np.random.random_sample()

0.9211111156563901

In [ ]:
type(np.random.random_sample())

float

In [ ]:
np.random.random_sample((5,))

array([0.90202035, 0.60630875, 0.15373777, 0.86313403, 0.42078372])

In [ ]:
np.random.rand(1)

array([0.11447432])

In [ ]:
np.random.rand(2, 3)

array([[0.36447448, 0.62336784, 0.83770828],
       [0.96798408, 0.50156134, 0.91970993]])

In [ ]:
np.random.randn(2, 3)

array([[ 0.6934026 , -0.40988039, -0.29346066],
       [ 0.00731871,  1.51932967, -0.41561844]])

In [ ]:
np.random.random_sample()

0.13122192085217144

In [ ]:
np.random.randint(1, 5, size = (3, 4))

array([[1, 2, 3, 3],
       [2, 4, 1, 4],
       [1, 4, 4, 4]])

In [ ]:
arr = np.random.randint(1, 5, size = (3, 4))

In [ ]:
arr

array([[4, 1, 1, 2],
       [3, 2, 3, 4],
       [4, 1, 3, 1]])

In [ ]:
arr.size

12

In [ ]:
arr.shape

(3, 4)

In [ ]:
arr.ndim

2

In [ ]:
arr

array([[4, 1, 1, 2],
       [3, 2, 3, 4],
       [4, 1, 3, 1]])

In [ ]:
arr.reshape(2, 6) #array size can not change, multiples of array size

array([[4, 1, 1, 2, 3, 2],
       [3, 4, 4, 1, 3, 1]])

In [ ]:
arr.reshape(6, 2)

array([[4, 1],
       [1, 2],
       [3, 2],
       [3, 4],
       [4, 1],
       [3, 1]])

In [ ]:
arr.reshape(12,)

array([4, 1, 1, 2, 3, 2, 3, 4, 4, 1, 3, 1])

In [ ]:
arr.reshape(12, 1)

array([[4],
       [1],
       [1],
       [2],
       [3],
       [2],
       [3],
       [4],
       [4],
       [1],
       [3],
       [1]])

In [ ]:
arr.reshape(12,2)

ValueError: cannot reshape array of size 12 into shape (12,2)

In [ ]:
arr.reshape(4, 3)

array([[4, 1, 1],
       [2, 3, 2],
       [3, 4, 4],
       [1, 3, 1]])

In [ ]:
arr.reshape(3,4)

array([[4, 1, 1, 2],
       [3, 2, 3, 4],
       [4, 1, 3, 1]])

In [ ]:
arr

array([[4, 1, 1, 2],
       [3, 2, 3, 4],
       [4, 1, 3, 1]])

In [ ]:
arr.reshape(4, -1)

array([[4, 1, 1],
       [2, 3, 2],
       [3, 4, 4],
       [1, 3, 1]])

In [ ]:
arr.reshape(4, -100)

array([[4, 1, 1],
       [2, 3, 2],
       [3, 4, 4],
       [1, 3, 1]])

In [ ]:
arr.reshape(3, -100)

array([[4, 1, 1, 2],
       [3, 2, 3, 4],
       [4, 1, 3, 1]])

In [ ]:
arr.reshape(-1, 4)

array([[4, 1, 1, 2],
       [3, 2, 3, 4],
       [4, 1, 3, 1]])

In [ ]:
arr

array([[4, 1, 1, 2],
       [3, 2, 3, 4],
       [4, 1, 3, 1]])

In [ ]:
arr.reshape(12, ).base

array([[4, 1, 1, 2],
       [3, 2, 3, 4],
       [4, 1, 3, 1]])

In [ ]:
arr

array([[4, 1, 1, 2],
       [3, 2, 3, 4],
       [4, 1, 3, 1]])

In [ ]:
arr.size

12

In [ ]:
arr.reshape(2, 2, 3)

array([[[4, 1, 1],
        [2, 3, 2]],

       [[3, 4, 4],
        [1, 3, 1]]])

In [ ]:
arr.reshape(1, 2, 2, 3)

array([[[[4, 1, 1],
         [2, 3, 2]],

        [[3, 4, 4],
         [1, 3, 1]]]])

In [ ]:
arr.reshape(4, 3, 1)

array([[[4],
        [1],
        [1]],

       [[2],
        [3],
        [2]],

       [[3],
        [4],
        [4]],

       [[1],
        [3],
        [1]]])

In [ ]:
arr.reshape(1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 3)

array([[[[[[[[[[[[4, 1, 1],
                 [2, 3, 2]],

                [[3, 4, 4],
                 [1, 3, 1]]]]]]]]]]]])

In [ ]:
lis = [1, 2, 3, 4]
arr = np.array(lis)

In [ ]:
arr

array([1, 2, 3, 4])

In [ ]:
arr.ndim

1

In [ ]:
arr2 = np.array([[2, 3], [4, 5]])
arr2

array([[2, 3],
       [4, 5]])

In [ ]:
arr2.ndim

2

In [ ]:
arr2 = np.zeros((3, 4))
arr2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
arr2.ndim

2

In [ ]:
arr3 = np.zeros((1, 3, 4)) # 3 rows, 4 columns >> 2d array + 1d
arr3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
arr3.ndim

3

In [ ]:
arr3.shape

(1, 3, 4)

In [ ]:
arr4 = np.zeros((1, 1, 3, 4)) # 3 rows, 4 columns >> 2d array + 1d +1d
arr4

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [ ]:
arr4.ndim

4

In [ ]:
arr4.shape

(1, 1, 3, 4)

In [ ]:
arr3 = np.zeros((3, 3, 4))
arr3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
arr3.ndim

3

In [ ]:
arr3.shape

(3, 3, 4)

In [ ]:
arr1 = np.random.randint(1, 10, (5, 6))

In [ ]:
arr1

array([[2, 7, 4, 4, 8, 3],
       [6, 4, 8, 4, 4, 2],
       [3, 7, 5, 7, 2, 3],
       [7, 4, 3, 5, 6, 8],
       [5, 9, 4, 8, 4, 4]])

In [ ]:
arr1 > 5

array([[False,  True, False, False,  True, False],
       [ True, False,  True, False, False, False],
       [False,  True, False,  True, False, False],
       [ True, False, False, False,  True,  True],
       [False,  True, False,  True, False, False]])

In [ ]:
arr1[arr1 > 5]

array([7, 8, 6, 8, 7, 7, 7, 6, 8, 9, 8])

In [ ]:
arr1[arr1 < 5]

array([2, 4, 4, 3, 4, 4, 4, 2, 3, 2, 3, 4, 3, 4, 4, 4])

In [ ]:
arr1

array([[2, 7, 4, 4, 8, 3],
       [6, 4, 8, 4, 4, 2],
       [3, 7, 5, 7, 2, 3],
       [7, 4, 3, 5, 6, 8],
       [5, 9, 4, 8, 4, 4]])

In [ ]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
arr[0]

array([0., 0., 0., 0.])

In [ ]:
arr[0]

array([0., 0., 0., 0.])

In [ ]:
arr1

array([[2, 7, 4, 4, 8, 3],
       [6, 4, 8, 4, 4, 2],
       [3, 7, 5, 7, 2, 3],
       [7, 4, 3, 5, 6, 8],
       [5, 9, 4, 8, 4, 4]])

In [ ]:
arr1[0:2, [0,2]] #0th - 1st row in continuation and 0th and 2nd column

array([[2, 4],
       [6, 8]])

In [ ]:
#slicing on both rows and column
arr1[0:2, 1:3]

array([[7, 4],
       [4, 8]])

In [ ]:
arr1[0:2, [0, 1]]

array([[2, 7],
       [6, 4]])

In [ ]:
arr

In [ ]:
arr1[0, [1,3]]

array([7, 1])

In [ ]:
arr1[2:4, [0, 2]]

array([[2, 4],
       [2, 9]])

In [ ]:
arr1

array([[3, 7, 7, 1, 5, 2],
       [6, 1, 5, 6, 6, 8],
       [2, 8, 4, 2, 9, 3],
       [2, 1, 9, 5, 8, 7],
       [6, 2, 7, 6, 6, 1]])

In [ ]:
arr1[2:5]

array([[2, 8, 4, 2, 9, 3],
       [2, 1, 9, 5, 8, 7],
       [6, 2, 7, 6, 6, 1]])

In [ ]:
arr1[2:5, 0:2] #slicing

array([[2, 8],
       [2, 1],
       [6, 2]])

In [ ]:
arr1[2:5, [0, 2]]

array([[2, 4],
       [2, 9],
       [6, 7]])

In [ ]:
arr1[[2,4]]

array([[2, 8, 4, 2, 9, 3],
       [6, 2, 7, 6, 6, 1]])

In [ ]:
arr1

array([[3, 7, 7, 1, 5, 2],
       [6, 1, 5, 6, 6, 8],
       [2, 8, 4, 2, 9, 3],
       [2, 1, 9, 5, 8, 7],
       [6, 2, 7, 6, 6, 1]])

In [ ]:
arr1

array([[3, 7, 7, 1, 5, 2],
       [6, 1, 5, 6, 6, 8],
       [2, 8, 4, 2, 9, 3],
       [2, 1, 9, 5, 8, 7],
       [6, 2, 7, 6, 6, 1]])

In [ ]:
arr1[[2, 4]] #selecting specific column

array([[2, 8, 4, 2, 9, 3],
       [6, 2, 7, 6, 6, 1]])

In [ ]:
arr1[2 : 4] #slicing

array([[2, 8, 4, 2, 9, 3],
       [2, 1, 9, 5, 8, 7]])

In [ ]:
arr1

array([[3, 7, 7, 1, 5, 2],
       [6, 1, 5, 6, 6, 8],
       [2, 8, 4, 2, 9, 3],
       [2, 1, 9, 5, 8, 7],
       [6, 2, 7, 6, 6, 1]])

In [ ]:
arr1[2:4, [1, 3]]

array([[8, 2],
       [1, 5]])

In [ ]:
arr1 = np.random.randint(1, 3, (3,3))
arr2 = np.random.randint(1, 3, (3,3))

In [ ]:
arr1

array([[1, 2, 2],
       [2, 2, 1],
       [2, 1, 1]])

##

In [ ]:
arr2

array([[2, 1, 1],
       [1, 1, 1],
       [2, 1, 2]])

In [ ]:
arr1 + arr2

array([[3, 3, 3],
       [3, 3, 2],
       [4, 2, 3]])

In [ ]:
arr1 - arr2

array([[-1,  1,  1],
       [ 1,  1,  0],
       [ 0,  0, -1]])

In [ ]:
arr1 * arr2

array([[2, 2, 2],
       [2, 2, 1],
       [4, 1, 2]])

In [ ]:
#matrix multiplication


arr1

array([[1, 2, 2],
       [2, 2, 1],
       [2, 1, 1]])

In [ ]:
arr2

array([[2, 1, 1],
       [1, 1, 1],
       [2, 1, 2]])

In [ ]:
arr1 @ arr2

array([[8, 5, 7],
       [8, 5, 6],
       [7, 4, 5]])

In [ ]:
arr1

array([[1, 2, 2],
       [2, 2, 1],
       [2, 1, 1]])

In [ ]:
arr2

array([[2, 1, 1],
       [1, 1, 1],
       [2, 1, 2]])

In [ ]:
arr1 / arr2 #index wise divison

array([[0.5, 2. , 2. ],
       [2. , 2. , 1. ],
       [1. , 1. , 0.5]])

In [ ]:
arr1

array([[1, 2, 2],
       [2, 2, 1],
       [2, 1, 1]])

In [ ]:
arr1 / 0

C:\Users\ajayk\AppData\Local\Temp\ipykernel_12284\824215542.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1 / 0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [ ]:
#Broad casting

In [ ]:
arr = np.zeros((3, 4))

In [ ]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
arr + 5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [ ]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
a = np.array([1, 2, 3, 4])

In [ ]:
a.shape

(4,)

In [ ]:
a

array([1, 2, 3, 4])

In [ ]:
arr + a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [ ]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
a

array([1, 2, 3])

In [ ]:
a = np.array([1, 2, 3])

In [ ]:
a = np.array([[1, 2, 3]])

In [ ]:
a.T

array([[1],
       [2],
       [3]])

In [ ]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
a

array([[1, 2, 3]])

In [ ]:
arr + a.T

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.]])

In [ ]:
a.T

array([[1],
       [2],
       [3]])

In [ ]:
a = np.array([1, 2, 3])
a.T

array([1, 2, 3])

In [ ]:
arr1

array([[1, 2, 2],
       [2, 2, 1],
       [2, 1, 1]])

In [ ]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.41421356],
       [1.41421356, 1.41421356, 1.        ],
       [1.41421356, 1.        , 1.        ]])

In [ ]:
np.log10(arr1)

array([[0.     , 0.30103, 0.30103],
       [0.30103, 0.30103, 0.     ],
       [0.30103, 0.     , 0.     ]])

In [ ]:
np.exp(arr1)

array([[2.71828183, 7.3890561 , 7.3890561 ],
       [7.3890561 , 7.3890561 , 2.71828183],
       [7.3890561 , 2.71828183, 2.71828183]])

In [ ]:
a

array([1, 2, 3])

In [ ]:
np.min(a)

1

In [ ]:
arr1

array([[1, 2, 2],
       [2, 2, 1],
       [2, 1, 1]])

In [ ]:
np.min(arr1)

1

In [ ]:
np.max(arr1)

2

In [ ]:
arr1

array([[1, 2, 2],
       [2, 2, 1],
       [2, 1, 1]])

In [ ]:
arr1.T

array([[1, 2, 2],
       [2, 2, 1],
       [2, 1, 1]])

In [ ]:
arr1.flatten() #reduce higher dimension to 1 d

array([1, 2, 2, 2, 2, 1, 2, 1, 1])

In [ ]:
#expand_dims >>  expands the array by inserting a new axis

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [1, 2, 3]])

In [ ]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

In [ ]:
np.sum(arr)

27

In [ ]:
np.sum(arr, axis = 0)

array([ 6,  9, 12])

In [ ]:
np.sum(arr, axis = 1)

array([ 6, 15,  6])

In [ ]:
#expand_dims >>expand the dimension of array
arr = np.array([1, 2, 3, 4])
arr

array([1, 2, 3, 4])

In [ ]:
arr.ndim

1

In [ ]:
arr1 = np.expand_dims(arr, axis = 0)
arr1

array([[1, 2, 3, 4]])

In [ ]:
arr1.ndim

2

In [ ]:
arr2 = np.expand_dims(arr1, axis = 0)
arr2

array([[[1, 2, 3, 4]]])

In [ ]:
arr2.shape

(1, 1, 4)

In [ ]:
arr

array([1, 2, 3, 4])

In [ ]:
arr1 = np.expand_dims(arr, axis = 1)
arr1

array([[1],
       [2],
       [3],
       [4]])

In [ ]:
arr = np.zeros((3, 4))

In [ ]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
arr1 = np.expand_dims(arr, axis = 1)
arr1

array([[[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]]])

In [ ]:
arr1 = np.expand_dims(arr, axis = 0)
arr1

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])