In [17]:
# pip install numpy

In [18]:
import numpy
import numpy as np
# what is numpy
# use case or feature of numpy
# numpy is a library for the Python programming language, adding support for large, multi-dimensional arrays and
# matrices, along with a large collection of high-level mathematical functions to operate on these arrays.

# numpy vs list
# numpy is faster and more memory efficient than lists for large datasets.
# numpy arrays are more suitable for numerical computations.
# numpy arrays are more suitable for scientific computing.
# numpy arrays are more suitable for data analysis.
# numpy arrays are more suitable for machine learning.
# numpy arrays are more suitable for data science.

# what is array
# use case or feature of array
# An array is a collection of elements of the same data type stored in contiguous memory locations.
# Arrays are used to store and manipulate large amounts of data.

Why is the Numpy Array so Fast?

Numpy arrays are written mostly in C language. Being written in C, the arrays are stored in contiguous memory locations which makes them accessible and easier to manipulate. This means that you can get the performance level of a C code with the ease of writing a Python program.

- Homogeneous Data: Arrays store elements of the same data type, making them more compact and memory-efficient than lists.
- Fixed Data Type: Arrays have a fixed data type, reducing memory overhead by eliminating the need to store type information for each element.
- Contiguous Memory: Arrays store elements in adjacent memory locations, reducing fragmentation and allowing for efficient access.

In [19]:
import numpy as np

a = np.array(5)

In [20]:
arr = np.array([2,3,4,5,6,7,8,9])
arr

array([2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
print(a)

5


In [22]:
type(a)

numpy.ndarray

In [23]:
l1 =['007x',12,12.4,True]

In [24]:
type(l1)
arr1 =np.array(l1)
arr1

array(['007x', '12', '12.4', 'True'], dtype='<U32')

In [25]:
type(l1[0])

str

In [26]:
type(l1[2])

float

In [27]:
type(arr[2])

numpy.int64

In [28]:
arr

array([2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
arr[5]= 23
arr

array([ 2,  3,  4,  5,  6, 23,  8,  9])

In [30]:
# sliceing
l1

['007x', 12, 12.4, True]

In [31]:
l1[start:end:step]

NameError: name 'start' is not defined

In [33]:
l1[:2]

['007x', 12]

In [30]:
l1[:2]

['007x', 12]

In [31]:
arr[:2]

array([2, 3])

In [34]:
arr[-1]

np.int64(9)

In [38]:
arr[-4::2]

array([6, 8])

In [44]:
arr3 =np.arange(1,7)
arr3

array([1, 2, 3, 4, 5, 6])

In [45]:
arr4= np.arange(11,16)
arr4

array([11, 12, 13, 14, 15])

In [46]:
arr3+arr4

ValueError: operands could not be broadcast together with shapes (6,) (5,) 

In [47]:
arr3.ndim #dimenstion

1

In [3]:
import numpy as np

In [4]:
np.__version__

'2.1.0'

In [5]:
arr = np.array([1,2,3,4,56])

In [6]:
arr.ndim

1

In [11]:
arr2d = np.array([ [1,2,3,4] ,[5,6,7,0]])
print(arr2d)

[[1 2 3 4]
 [5 6 7 0]]


In [8]:
arr2d.ndim

2

In [14]:
arr3d = np.array([[ [1,2,3,4] ,[5,6,7,0]]])
print(arr3d)
arr3d.ndim

[[[1 2 3 4]
  [5 6 7 0]]]


3

In [18]:
arr3d = np.array([[ [1,2,3,4] ,[5,6,7,0]],[ [1,2,3,4] ,[5,6,4,34]]])
print(arr3d)
arr3d.ndim

[[[ 1  2  3  4]
  [ 5  6  7  0]]

 [[ 1  2  3  4]
  [ 5  6  4 34]]]


3

In [27]:
arr3d.shape

(2, 2, 4)

In [19]:
arr = np.array([[[[[1,2,3,4,56]]]]])

In [20]:
arr.ndim

5

In [24]:
arr2 = np.array([1,2,3,4,5,8,9],ndmin=6)

In [25]:
arr2.ndim

6

In [26]:
arr2.shape

(1, 1, 1, 1, 1, 7)

In [28]:
arr2

array([[[[[[1, 2, 3, 4, 5, 8, 9]]]]]])

In [29]:
arr2d = np.array([ [1,2,3,4] ,[5,6,7,0]])
print(arr2d)

[[1 2 3 4]
 [5 6 7 0]]


In [36]:
arr2d[0][2:4]

array([3, 4])

In [33]:
arr2d[0,2]

np.int64(3)

In [37]:
arr2d[0,2:4]

array([3, 4])

In [38]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])


6


In [43]:
arr4 = np.array([9,56,8,5] ,dtype="f")

In [44]:
arr4

array([ 9., 56.,  8.,  5.], dtype=float32)

In [46]:
arr4.dtype

dtype('float32')

In [47]:
arr4.astype("i")

array([ 9, 56,  8,  5], dtype=int32)

In [48]:
arr4 = arr4.astype("i")

In [49]:
arr4.dtype

dtype('int32')

In [51]:
arr4.size

4

In [52]:
arr5 = arr4.copy()

In [56]:
arr5

array([ 9, 56,  8,  5], dtype=int32)

In [54]:
arr4[0]= 10

In [55]:
arr4

array([10, 56,  8,  5], dtype=int32)

In [60]:
arr6 = arr4
arr6

array([20, 56,  8,  5], dtype=int32)

In [61]:
arr4[0]=10
arr4

array([10, 56,  8,  5], dtype=int32)

In [62]:
arr6

array([10, 56,  8,  5], dtype=int32)

In [66]:
print(arr6.base)

None


In [69]:
arr7 = arr4.view()
arr7

array([10, 56,  8,  5], dtype=int32)

In [71]:
print(arr7.base)

[10 56  8  5]


In [19]:
# types of array creation

# 2.arange
arr1 = np.arange(1, 13,dtype="i",)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12], dtype=int32)

In [22]:
# linespace arr
arr2= np.linspace(0,5, 10)
arr2


array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [25]:
# empty 
arr4 = np.empty((2,3))
arr4

array([[8.03531361e-042, 3.12249488e-321, 0.00000000e+000],
       [6.96100713e-312, 0.00000000e+000, 2.05833624e-312]])

In [26]:
#zeros
arr5 = np.zeros((4,4))
arr5

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [28]:
arr6 = np.ones(2)
arr6

array([1., 1.])

In [29]:
arr6 = np.ones((2,2))
arr6

array([[1., 1.],
       [1., 1.]])

In [33]:
# full 
arr7 = np.full((2,2),"a")
arr7

array([['a', 'a'],
       ['a', 'a']], dtype='<U1')

In [35]:
# random array create
arr8 =np.random.rand(2,3)
arr8

array([[0.37838786, 0.56615259, 0.15129468],
       [0.81638091, 0.69943647, 0.33224785]])

In [37]:
arr9 = np.random.randint(1,10)
arr9

2

In [41]:
arr10 = np.random.randint(1,10, size=(2,3))
arr10

array([[4, 5, 2],
       [9, 6, 5]], dtype=int32)

In [43]:
arr11 = np.random.random((2,2,3))
arr11

array([[[0.95949028, 0.0370232 , 0.11623095],
        [0.5573588 , 0.92728074, 0.07199559]],

       [[0.4865206 , 0.51992753, 0.52138435],
        [0.15962531, 0.14956939, 0.20086114]]])

In [46]:
arr12= np.random.randn(2,4)
print(arr12)

[[-1.22992705 -1.11914996 -0.97039151  1.02232302]
 [ 0.98811591  0.74500182  0.96190954  0.71677471]]


In [32]:
import numpy as np

In [33]:
# 2.arange
arr1 = np.arange(1, 13,dtype="i",)

arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12], dtype=int32)

In [34]:
arr1.size

12

In [35]:
arr2d = arr1.reshape((4,3))  # convert 1Dinto  2D array
arr2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]], dtype=int32)

In [36]:
arr3d = arr1.reshape((2,2,3))  # convert 1D into  3D array

In [37]:
#  2d to 3d
arr2d.reshape((3,2,2))

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]], dtype=int32)

In [38]:
#3d to 1d
arr3d.reshape(12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12], dtype=int32)

In [39]:
#nd to 1d
arr3d.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12], dtype=int32)

In [40]:
arr1.reshape((-1,4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]], dtype=int32)

In [41]:
arr1.reshape((-1,2,2))

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]], dtype=int32)

In [42]:
for a in arr2d:
    print(a)
    print("=====")

[1 2 3]
=====
[4 5 6]
=====
[7 8 9]
=====
[10 11 12]
=====


In [43]:
for a in arr2d:
    for t in a:
        print(t)
        print("=====")

1
=====
2
=====
3
=====
4
=====
5
=====
6
=====
7
=====
8
=====
9
=====
10
=====
11
=====
12
=====


In [44]:
for a in arr3d:
    for t in a:
        print(t)
        print("=====")

[1 2 3]
=====
[4 5 6]
=====
[7 8 9]
=====
[10 11 12]
=====


In [45]:
for a in arr3d:
    for t in a:
        for p  in t:
            print(p)
            print("=====")

1
=====
2
=====
3
=====
4
=====
5
=====
6
=====
7
=====
8
=====
9
=====
10
=====
11
=====
12
=====


In [46]:
# nditer fuction to  get the number of iterations 
# 
for  i in np.nditer(arr3d):
    print(i) 

1
2
3
4
5
6
7
8
9
10
11
12


In [47]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr1+arr2

array([5, 7, 9])

In [48]:
np.sqrt(arr1)

array([1.        , 1.41421356, 1.73205081])

In [49]:
np.sum(arr1)

np.int64(6)

In [50]:
np.mean(arr1)

np.float64(2.0)

In [51]:
np.median(arr1)

np.float64(2.0)

In [52]:
arr2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]], dtype=int32)

In [53]:
# total sum  of all elements in the array
np.sum(arr2d)

np.int64(78)

In [54]:
# total sum row wise
np.sum(arr2d, axis=1)

array([ 6, 15, 24, 33])

In [ ]:
import numpy as np

arr2d = np.arange(1,13)
arr2d = arr2d.reshape((4,3))
arr2d

In [ ]:
# total sum column wise
np.sum(arr2d, axis=0).astype("f")

In [56]:
#  total mean/average of array
np.mean(arr2d)

np.float64(6.5)

In [57]:
#  total mean/average of array row-wise
np.mean(arr2d,axis=1)

array([ 2.,  5.,  8., 11.])

In [58]:
#  total mean/average of array column-wise
np.mean(arr2d,axis=0)

array([5.5, 6.5, 7.5])

In [ ]:
arr = np.random.randint(12, size=(3,4))
arr

In [82]:
arr

array([[ 5, 10,  4, 11],
       [10, 10,  5,  9],
       [ 4,  0,  2,  6]], dtype=int32)

In [80]:
np.sort(arr,axis=None)

array([ 0,  2,  4,  4,  5,  5,  6,  9, 10, 10, 10, 11], dtype=int32)

In [79]:
np.sort(arr ,axis=0)

array([[ 4,  0,  2,  6],
       [ 5, 10,  4,  9],
       [10, 10,  5, 11]], dtype=int32)

In [81]:
np.sort(arr ,axis=1)

array([[ 4,  5, 10, 11],
       [ 5,  9, 10, 10],
       [ 0,  2,  4,  6]], dtype=int32)

In [92]:
arr = np.array([12, 2, np.nan, np.inf])
arr

array([12.,  2., nan, inf])

In [93]:
np.isnan(arr)

array([False, False,  True, False])

In [94]:
np.isfinite(arr)

array([ True,  True, False, False])

In [96]:
arr

array([12.,  2., nan, inf])

In [97]:
sums =0
for i in arr:
    if np.isfinite(i):
        sums=sums+i
sums

np.float64(14.0)

In [110]:
arr1 =np.array([1,2,3,7])
arr2 =np.array([8,5,0])

In [111]:
arr1.shape

(4,)

In [112]:
arr2.shape

(3,)

In [131]:
arr1 =np.array([1,2,3])
arr2 =np.array([[8],[4],[5]])

In [132]:
arr1.shape

(3,)

In [134]:
arr2.shape

(3, 1)

In [135]:
arr1+arr2

array([[ 9, 10, 11],
       [ 5,  6,  7],
       [ 6,  7,  8]])

In [145]:
arr1 =np.array([1,2,3])
arr2 =np.array([[8,]])

In [146]:
arr2.shape

(1, 1)

In [147]:
arr1.shape

(3,)

In [148]:
arr1+arr2

array([[ 9, 10, 11]])

In [154]:
arr3= np.array([[2,3,4,5,6,3]])

In [151]:
arr

array([[2, 3, 4, 5, 6]])

In [ ]:
arr3.T

In [156]:
arr= np.matrix([2,3,4,5,6,7])

In [158]:
arr2 =np.matrix([3,5,7,8,9,9])

In [159]:
arr+arr2

matrix([[ 5,  8, 11, 13, 15, 16]])

In [ ]:
arr*arr2

In [171]:
arr*arr2.T

matrix([[206]])

In [170]:
arr2* arr2

ValueError: shapes (1,6) and (1,6) not aligned: 6 (dim 1) != 1 (dim 0)

In [168]:
arr3

array([[2, 3, 4, 5, 6, 3]])

In [169]:
arr3*arr3

array([[ 4,  9, 16, 25, 36,  9]])

In [1]:
import numpy as np
arr4= np.array([[2,3,4],[5,6,7]])
arr5= np.array([[2,5,8],[5,8,7]])

In [2]:
arr4

array([[2, 3, 4],
       [5, 6, 7]])

In [4]:
arr5

array([[2, 5, 8],
       [5, 8, 7]])

In [5]:
arr4*arr5

array([[ 4, 15, 32],
       [25, 48, 49]])

In [6]:
np.dot(arr4,arr5.T)

array([[ 51,  62],
       [ 96, 122]])

In [7]:
 # Example of a system of linear equations: Ax = b
A = np.array([[3, 2], [1, 2]])
b = np.array([8, 7])

# Solve for x
x = np.linalg.solve(A, b)
print("Solution:", x)

Solution: [0.5  3.25]


In [13]:
# y =mx+c 
X = np.array([[1, 2], [3, 4], [5, 6]])
M = np.array([[0.5], [1]])
c = np.array([1])
y= np.dot(X,M) +c
y


array([[3.5],
       [6.5],
       [9.5]])

In [ ]:
y =X @ M +c

In [18]:

c = np.array([[1,2,4],[3,3,4], [2,3,4]])

np.linalg.det(c)

np.float64(4.000000000000003)