In [23]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [26]:
arr.reshape(2,-1)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [ ]:
#  Reshaping a 2D Array into a 1D Array
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Flattening the array
newarr = arr.reshape(-1)
print(newarr)

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

# Reshape into 2 layers, each with 2 rows and 3 columns
newarr = arr.reshape(2, 2, 3)
print(newarr)


In [8]:
np.matrix([[[1, 2], [5, 6], [7, 8]]])

matrix([[1, 2],
        [5, 6],
        [7, 8]])

In [7]:
np.array([[[1, 2], [5, 6], [7, 8]]])

array([[[1, 2],
        [5, 6],
        [7, 8]]])

In [ ]:
np.matrix([[1, 2], [5, 6], [7, 8]])

In [10]:
# If the input is already an array, no copy is made
arr = np.array([1, 25, 3])
arr2 = np.asarray(arr)

print(arr2)


[ 1 25  3]


In [13]:
# If the input is already an array, no copy is made
arr = np.array([1, 25, 3])
arr2 = np.asarray([1,4])

print(arr2)
type(arr2)



[1 4]


numpy.ndarray

In [20]:
# Example with np.matrix (a subclass of ndarray)
mat = np.matrix([[1, 2], [3, 4]])
arr = np.asanyarray([[2,2]])

print(type(arr))  # Output: <class 'numpy.matrix'>


<class 'numpy.ndarray'>


In [27]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)


1
2
3
4
5
6
7
8


In [39]:
# indexing
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
arr[1]
arr[-1]
arr[::2]

array([[[1, 2],
        [3, 4]]])

In [36]:
rr_zeros = np.zeros((3, 4))  # 3 rows and 4 columns

# With ones
arr_ones = np.ones((2, 3))  # 2 rows and 3 columns
# With a range of values
arr_range = np.arange(0, 10, 2)  # start, stop, step
# With equally spaced values
arr_linspace = np.linspace(0, 1, 5)  # start, stop, number of values
# With random values
arr_random = np.random.rand(3, 2)  # 3 rows and 2 columns with values between 0 and 1
print(np.full((2,3),5))
print(np.empty((2,2)))
print(np.zeros((2,2)))
print("4")
print(np.arange(1,10,2))
print(np.random.randint(1,10))
print(np.random.randn(3, 2)) 
print(np.diag([1,2,3,4]))
print(rr_zeros)
print(arr_ones)
print(arr_range)
print(arr_linspace)
print(arr_random)

[[5 5 5]
 [5 5 5]]
[[0.25 0.5 ]
 [0.75 1.  ]]
[[0. 0.]
 [0. 0.]]
4
[1 3 5 7 9]
5
[[ 0.31378991  1.08945442]
 [ 0.09309422 -0.15998993]
 [-0.73495863 -0.59307737]]
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
[[0.24376415 0.10015434]
 [0.3534212  0.40714934]
 [0.63594636 0.12549312]]


In [4]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
# Element-wise addition
result_add = arr1 + arr2
# Element-wise subtraction
result_subtract = arr1 - arr2
# Element-wise multiplication
result_multiply = arr1 * arr2
# Element-wise division
result_divide = arr1 / arr2
# Element-wise power
result_power = arr1 ** arr2
print(result_add)


[5 7 9]


In [6]:
# Broadcasting allows NumPy to perform element-wise operations on arrays of different shapes and sizes:
import numpy as np

arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([10, 20, 30])

# Broadcasting the addition
result_broadcast = arr1 + arr2
result_broadcast


array([[11, 22, 33],
       [14, 25, 36]])

In [9]:
array1 = [1, 2, 3]
array2 = [[1], [2], [3]]
result = array1 + array2
result

# create 1-D array
array1 = np.array([1, 2, 3])

# create 2-D array
array2 = np.array([[1], [2], [3]])

# add arrays of different dimension
# size of array1 expands to match with array2
sum = array1 + array2

print(sum)

[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [7]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
# Minimum and maximum
result_min = np.min(arr)
result_max = np.max(arr)
# Sum and product
result_sum = np.sum(arr)
# result_sum1 = np.sum(arr,axis=1)
result_product = np.prod(arr)
# Mean and median
result_mean = np.mean(arr)
result_median = np.median(arr)
# Variance and standard deviation
result_var = np.var(arr)
result_std = np.std(arr)


AxisError: axis 1 is out of bounds for array of dimension 1

In [42]:
# NumPy offers numerous functions to manipulate arrays:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
# Transpose
arr_transposed = arr.T
# Reshape
arr_reshaped = arr.reshape((3, 2))
# Flatten
arr_flattened = arr.flatten()
# Concatenate
arr_concatenated = np.concatenate((arr, arr), axis=1)


In [46]:
# NumPy provides a comprehensive set of linear algebra functions:
import numpy as np
# Matrix multiplication
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
result_matrix_mult = np.dot(matrix1, matrix2)
# Determinant
det = np.linalg.det(matrix1)
# Inverse
inv = np.linalg.inv(matrix1)
print(result_matrix_mult)
print(det)
print(inv)

[[19 22]
 [43 50]]
-2.0000000000000004
[[-2.   1. ]
 [ 1.5 -0.5]]


In [3]:
import numpy as np
# np.sort(): Sort an array in ascending order.
# np.argsort(): Return the indices that would sort an array.
# np.searchsorted(): Find the indices to insert elements to maintain order.
arr = np.array([[1, 2, 3], [4, 5, 6]])
np.sort(arr)
arr = np.array([[1, 23, 3], [4, 5, 6]])
np.sort(arr)
np.argsort(arr)
# np.searchsorted(arr)
import numpy as np

arr = np.array([1, 3, 5, 7])
values = np.array([2, 43, 6])

# np.searchsorted(a, v, side='left', sorter=None)
# Find insertion indices for values to maintain the sorted order
indices = np.searchsorted(arr, values)
print(indices)


[1 0 3]


In [ ]:
# Statistics and Data Analysis
np.mean(): #Compute the mean of an array.
np.median(): #Compute the median of an array.
np.percentile(): Compute the q-th percentile of the data along the specified axis.
np.cov(): Compute the covariance matrix.
np.corrcoef(): Compute the correlation coefficient matrix.
np.histogram(): Compute the histogram of a set of data.
