In [ ]:
pip install numpy 

In [1]:
import numpy

In [2]:
numpy.__version__

'2.1.0'

In [4]:
!pip3 install numpy --upgrade

Defaulting to user installation because normal site-packages is not writeable


In [5]:
li = [1,2,3,4,5,6]

In [6]:
print(li)
print(type(li))

[1, 2, 3, 4, 5, 6]
<class 'list'>


In [8]:
arr = numpy.array(li)  # list variabl pass 

abc =numpy.array([12,23,4,5,5,6])   # list data

abc =numpy.array((12,23,4,5,5,6))  # tuple data
print(arr)
print(type(arr))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [11]:
a= numpy.array(12)

In [13]:
type(a)

numpy.ndarray

In [14]:
a.ndim

0

In [26]:
arr.ndim
nd = numpy.array([
    [1,2,3,4]
    ])
print(nd.ndim)
print(nd.shape)

2
(1, 4)


In [27]:
nd = numpy.array([
    [1,2,3,4],
    [7,8,9,0]
    ])
print(nd.ndim)
print(nd.shape)

2
(2, 4)


In [28]:
nd = numpy.array([[
    [1,2,3,4],
    [7,8,9,0]
    ]])
print(nd.ndim)
print(nd.shape)

3
(1, 2, 4)


In [29]:
nd = numpy.array([[[
    [1,2,3,4],
    [7,8,9,0]
    ]]])
print(nd.ndim)
print(nd.shape)

4
(1, 1, 2, 4)


In [58]:
nd = numpy.array([[[
    [1,2,3],
    [7,8,9],
    [1,2,4],
    [7,9,0]
    ]]])
print(nd.ndim)
print(nd.shape)

4
(1, 1, 4, 3)


In [7]:
import numpy
arr = numpy.array([
    [[1, 2, 3], 
    [4, 5, 6]], 
    
    [[1, 14, 3], 
     [4, 12, 6]],

     [[1, 22, 3], 
     [4, 51, 6]]

     ])

# print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.size)

3
(3, 2, 3)
18


In [47]:
numpy.array([1,2,3,4],ndmin=5)

array([[[[[1, 2, 3, 4]]]]])

In [1]:
51 +20


71

In [3]:
import numpy
arr1 = numpy.array([1,2,3,4])
arr2 =  numpy.array([5,6,7,8])
arr1+arr2


array([ 6,  8, 10, 12])

In [9]:
# 3x +4 y =3
# 4x + 3y =6
import numpy as np

x,y=3,2

coff= np.array([[3, 4]
                ,[4, 3]])
var =np.array([x,y])
b = np.array([3, 6])




In [11]:
coff @ var

array([17, 18])

In [16]:
coff[1][0]
coff[1,0]

np.int64(4)

In [26]:
coff= np.array([[3, 4,5,6],
                [4, 3,7,9],
                [12,343,45,2]
                ])

coff


array([[  3,   4,   5,   6],
       [  4,   3,   7,   9],
       [ 12, 343,  45,   2]])

In [37]:
coff[1:3]
coff[1:3][1][1:3]

array([343,  45])

In [43]:
# for i in coff:
#     for j in i:
#         print(j)

for index,i in enumerate(np.nditer(coff)):
    print(index, i)

0 3
1 4
2 5
3 6
4 4
5 3
6 7
7 9
8 12
9 343
10 45
11 2


## slicing

In [16]:
li =[1, 2, 3, 4, 5, 6,[1, 2, 3, 4], 5, 6]

In [21]:
li[6][2]

3

In [9]:
li[0:3]

[1, 2, 3]

In [55]:
# li[2:4]

[3, 4]

In [54]:
li[4:]

[5, 6]

In [49]:
li[3]

4

In [52]:
arr[1][0][1]

np.int64(14)

In [22]:
import numpy as np

In [40]:
arr = np.array([
    [[1, 2, 3], 
    [4, 5, 6]],

    [[7, 8, 9], 
     [10, 11, 12]],

      [[7, 8, 9], 
     [10, 11, 12]]
    ])

print(arr[0, 1, 2])

6


In [41]:
arr[0:2]

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [43]:
arr[0][1][0:2]
arr[0,1,0:2]

array([4, 5])

In [44]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


In [55]:
d =np.array([1,2,4,'232'], dtype="i")
d

array([  1,   2,   4, 232], dtype=int32)

In [56]:
d.astype("i")

array([  1,   2,   4, 232], dtype=int32)

In [57]:
d.dtype

dtype('int32')

In [44]:
d =np.array([1,2,644,'232'], dtype="i")

In [55]:
#  deep copy
e = d.copy()
print(e)

e.view()

[  1   2 644 232]


array([  1,   2, 644, 232])

In [56]:
# shallow copy
f =d
print(f)

f.view()

[  1   2 644 232]


array([  1,   2, 644, 232], dtype=int32)

In [67]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [77]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(-1, 3) # (3,-1)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [75]:
# reshaping
#  Reshaping a 2D Array into a 1D Array
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Flattening the array
newarr = arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6]


In [82]:
# 1D 3d
d3 = arr.reshape(2, 3, 2)

In [83]:
d3.ndim

3

In [85]:
d3.shape

(2, 3, 2)

In [87]:
for i in arr:
    print   (i)

1
2
3
4
5
6
7
8
9
10
11
12


In [92]:

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in (arr):
  for j in x:[[]]
    for  k in j:
        print(k)


1
2
3
4
5
6
7
8


In [97]:
for x in np.nditer(arr):
  print(x)


1
2
3
4
5
6
7
8


In [94]:

for x in (arr):
    print(x)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [95]:

for x in (arr):
  for j in x:
    print(j)

[1 2]
[3 4]
[5 6]
[7 8]


In [98]:
arr_zeros = np.zeros((3, 4))  # 3 rows and 4 columns
arr_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [100]:

# With ones
arr_ones = np.ones((2, 3))  # 2 rows and 3 columns
arr_ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [102]:

# With a range of values
arr_range = np.arange(0, 10, 2)  # start, stop, step
print(arr_range)  # [0 2 4 6 8]
# With equally spaced values
arr_linspace = np.linspace(0, 1, 5)  # start, stop, number of values
print(arr_linspace)  # [0.  0.25 0.5
# With random values
arr_random = np.random.randn(3, 2)  # 3 rows and 2 columns with values between 0 and 1
print(arr_random)


[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
[[-1.46451188 -0.44211872]
 [ 2.91614762  0.05394308]
 [-0.41805201 -1.57215478]]


In [1]:
# NumPy supports various element-wise mathematical operations on arrays:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
# Element-wise addition
result_add = arr1 + arr2
print(result_add)
# ---
# Element-wise subtraction
result_subtract = arr1 - arr2
print(result_subtract)

# Element-wise multiplication
result_multiply = arr1 * arr2
print(result_multiply)

# Element-wise division
result_divide = arr1 / arr2
print(result_divide)
# Element-wise power
result_power = arr1 ** arr2
print(result_power)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]


In [2]:
arr1 = np.array([1, 2, 3])
np.sum(arr1)

np.int64(6)

In [3]:
np.mean(arr1)

np.float64(2.0)

In [4]:
arr1

array([1, 2, 3])

In [7]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
# Square root
result_sqrt = np.sqrt(arr)
print(result_sqrt)
# Exponential
result_exp = np.exp(arr)
print(result_exp)
# Trigonometric functions
result_sin = np.sin(arr)
print(result_sin)
result_cos = np.cos(arr)
print(result_cos)
# Sum and mean
result_sum = np.sum(arr)
print(result_sum)
result_mean = np.mean(arr)
print(result_mean)


[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
15
3.0


In [9]:
import numpy as np

# create two matrices
matrix1 = np.array([[1, 3], 
             		[5, 7]])
             
matrix2 = np.array([[2, 6], 
                    [4, 8]])

# calculate the dot product of the two matrices
result = np.dot(matrix1, matrix2)

print("matrix1 x matrix2: \n",result)

matrix1 x matrix2: 
 [[14 30]
 [38 86]]


In [10]:
matrix1 = np.array([[1, 3], 
             		[5, 7]])
matrix1.transpose()

array([[1, 5],
       [3, 7]])

In [15]:
# boolean indexingarr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([10, 20, 30])

# Broadcasting the addition
result_broadcast = arr1 + arr2

matrix1>4

array([[False, False],
       [ True,  True]])

In [14]:
matrix1[matrix1>4]

array([5, 7])

In [21]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([10, 20,6])

# Broadcasting the addition
result_broadcast = arr1 + arr2
result_broadcast

array([[11, 22,  9],
       [14, 25, 12]])

In [22]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
# Flatten
arr_flattened = arr.flatten()
arr_flattened

array([1, 2, 3, 4, 5, 6])

In [25]:
# Concatenate
arr_concatenated = np.concatenate((arr, arr))
arr_concatenated

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [26]:
# Concatenate
arr_concatenated = np.concatenate((arr, arr), axis=0)
arr_concatenated

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [27]:
# Concatenate
arr_concatenated = np.concatenate((arr, arr), axis=1)
arr_concatenated

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [30]:
arr_add = np.sum((arr, arr), axis=0)
arr_add

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [31]:
arr_add = np.sum((arr, arr), axis=1)
arr_add

array([[5, 7, 9],
       [5, 7, 9]])

In [33]:
arr = np.array([[1, 12, 3], [14, 5, 6]])
np.sort(arr)

array([[ 1,  3, 12],
       [ 5,  6, 14]])

In [34]:
np.argsort(arr)

array([[0, 2, 1],
       [1, 2, 0]])

In [35]:
arr = np.array([1, 3, 5, 7])
values = np.array([2, 43, 6])

indices = np.searchsorted(arr, values)
print(indices)

[1 4 3]


In [1]:
import numpy as np
np.__version__

'2.1.0'

In [3]:
pip uninstall numpy

^C
Note: you may need to restart the kernel to use updated packages.


In [2]:
import pandas as pd


A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\ProgramData\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "c:\ProgramData\anaconda3\Lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "c:\ProgramData\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 701, in start
    self.io_loop.start()
  File "c:\ProgramData\anaconda3\Lib\site-pack

ImportError: 
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.




A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\ProgramData\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "c:\ProgramData\anaconda3\Lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "c:\ProgramData\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 701, in start
    self.io_loop.start()
  File "c:\ProgramData\anaconda3\Lib\site-pack

ImportError: 
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.



ImportError: numpy.core.multiarray failed to import

In [37]:
!pip install pandas

Defaulting to user installation because normal site-packages is not writeable


In [39]:
import pandas 


A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\ProgramData\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "c:\ProgramData\anaconda3\Lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "c:\ProgramData\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 701, in start
    self.io_loop.start()
  File "c:\ProgramData\anaconda3\Lib\site-pack

ImportError: 
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.



ImportError: numpy.core.multiarray failed to import

In [40]:
pip install --upgrade numpy


Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.
