## Prepared by Sanasam Ranbir Singh

# How to define tensors?
***
<div class="alert alert-block alert-danger">
    <font size=5><b> Import TensorFlow module</b></font>
</div>

<font size=4>For using tensorflow, we would need to <b>import the tensorflow</b> module first as follows.</font>

In [1]:
import tensorflow as tf                   # tensorflow is imported as object tf
print("The version is " + tf.__version__) # print the version. I have used 2.x

The version is 2.18.0


 
 <br><br>
 
 

<div class="alert alert-block alert-danger">
    <font size=5><b> Types of Tensors</b></font>
</div>

### Four Types
> <font size=4>1. Constant</font><br>
> <font size=4>2. Variable</font><br>
> <font size=4>3. Placeholder</font><br>
> <font size=4>4. SparseTensor</font>

<font size=4>In today's lesson, we will define tensor using <b>constant</b> tensor type. Other types of tensors, we will discuss in the subsequent lessons.</font>
## Constant Tensor
___


<font size=4>A <b>Constant</b> tensor is created using <b>tf.constant()</b> method. As the name suggest, once created, the value of constant type tensor can not be changed. </font>

<font size=4><b><i>Syntex</i></b><br>
> tf.constant ( value, dtype=None, shape=None, name='Const')</font>

<font size=4><b><i>Attributes</i></b>:<br>
> <b>value</b>: A constant value (or list) of output type dtype.<br>
> <b>dtype</b>: The type of the elements of the resulting tensor.<br>
> <b>shape</b>: Optional dimensions of resulting tensor.<br>
> <b>name</b>: Optional name for the tensor.</font>

<font size=4><b><i>Return</i></b><br>
> It returns a Constant Tensor</font>




<div class="alert alert-block alert-danger">
    <font size=5><b>Data Types</b></font>
</div>

<div>
<img src="attachment:image.png" width=500 align="left"/>
</div>
<br><br>

<div class="alert alert-block alert-danger">
    <font size=5><b>Define a Scalar Tensor</b></font>
</div>

A scalar tensor stores a scalar value wich can be a number, a string, a boolean value.

It has no direction associated with it. That means,
- Rank (dimension) = 0 <br>
- Shape = 0

Some examples of scalar tensors are defined below.

In [2]:
x = tf.constant(5)  # Integer value
print(x)

tf.Tensor(5, shape=(), dtype=int32)


In [3]:
x = tf.constant(5.0)
print(x)

tf.Tensor(5.0, shape=(), dtype=float32)


In [4]:
x = tf.constant("Tensor Definition")
print(x)

tf.Tensor(b'Tensor Definition', shape=(), dtype=string)


In [5]:
x = tf.constant(True)
print(x)

tf.Tensor(True, shape=(), dtype=bool)


<div class="alert alert-block alert-danger">
    <font size=5><b>Vector Tensor (1 Dimensional Tensor)</b></font>
</div>

It has data with only one direction i.e., coordinate space. The following figure defines four data points in one direction, which can be realized by a vector of [1,3,6,8].<br>
<img src="attachment:image-3.png" align="left"/><br><br><br>

All the data points lies in a the same direction, it means,
- Rank (dimention)= 1
- Shape = $n$; $n$ is the number of the elements in the vector.

It defines vectors such as vector of,
> - Integers:  [1, 2, 3]
>  - Rank=1, Shape=3
> - Floats: [2.0, 4.0, 6.0, 8.0]
>  - Rank=1, Shape=4
> - String: ["Tom", "John", "Sally"]
>  - Rank=1, Shape=3

<font color='red'><b>1D tensor is a vector of 0D Tensors.</b></font> Few examples are defined below.


In [6]:
x = tf.constant([2, 4, 6])      # A Rank 1 tensor of shape 3 with integer values. 
print(x)

tf.Tensor([2 4 6], shape=(3,), dtype=int32)


In [7]:
x = tf.constant([2.0, 4.0, 6.0, 8.0])   # A Rank 1 tensor of shape 4  with real values.
print(x)

tf.Tensor([2. 4. 6. 8.], shape=(4,), dtype=float32)


In [8]:
x = tf.constant(["Tom", "John", "Sally"])   # A Rank 1 tensor of shape 4  with string values.
print(x)

tf.Tensor([b'Tom' b'John' b'Sally'], shape=(3,), dtype=string)


<div class="alert alert-block alert-danger">
    <font size=5><b>Matrix Tensor (2 Dimensional Tensor)</b></font>
</div>


<b>Rank = 2, shape = ($n$,$m$); $n$ and $m$ are positive natural numbers </b>

<font color='red'><b> 2D tensor is a vector of 1D tensor</b></font>

In [9]:
y = tf.constant([[1, 2, 3, 4],[5,6,7,8]])
print(y)

tf.Tensor(
[[1 2 3 4]
 [5 6 7 8]], shape=(2, 4), dtype=int32)


<div class="alert alert-block alert-danger">
    <font size=5><b>3 Dimensional Tensor</b></font>
</div>


<b>Rank = 3, shape = ($l$,$n$,$m$); $l$, $n$ and $m$ are positive natural numbers </b>

<font color='red'><b> 3D tensor is a vector of 2D tensor</b></font>

In [10]:
y = tf.constant([[[1, 2, 3, 4],[5,6,7,8]],[[1, 2, 3, 4],[5,6,7,8]],[[1, 2, 3, 4],[5,6,7,8]]])
print(y)

tf.Tensor(
[[[1 2 3 4]
  [5 6 7 8]]

 [[1 2 3 4]
  [5 6 7 8]]

 [[1 2 3 4]
  [5 6 7 8]]], shape=(3, 2, 4), dtype=int32)


<div class="alert alert-block alert-danger">
    <font size=5><b>Generalization</b></font>
</div>

<b>We can define a tensor $x$ of dimension $k$ with the shape ($n_{k}$,$n_{k-1}$, $n_{k-2}$,$n_{k-3}$,...,$n_{1}$) </b>
> <b>as a vector with $n_{k}$ number of $k-1$ Dimemsional tensors of shape ($n_{k-1}$, $n_{k-2}$,$n_{k-3}$,...,$n_{1}$) </b>

<b>Recursively, a tensor of dimension $k-1$ shape ($n_{k-1}$, $n_{k-2}$,$n_{k-3}$,...,$n_{1}$) can be defined </b>
> asas a vector with $n_{k-1}$ number of $k-2$ Dimemsional tensors of shape ($n_{k-2}$,$n_{k-3}$,...,$n_{1}$), and so on... </b> 

<div class="alert alert-block alert-danger">
    <font size=5><b>Summary</b></font>
</div>

1. Rank/Degree of a tensor defines the number of associated dirctions or dimenssions.

In [11]:
y = tf.constant([[1, 2, 3, 4],[5,6,7,8]])
tf.rank(y)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

2. Shape of a tensor defines the number of element in each of the dirctions or dimenssions.

In [12]:
y = tf.constant([[1, 2, 3, 4],[5,6,7,8]])
tf.shape(y)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 4], dtype=int32)>

3. The value of a tensor can be printed as

In [13]:
y = tf.constant([[1, 2, 3, 4],[5,6,7,8]])
tf.print(y)

[[1 2 3 4]
 [5 6 7 8]]
