In [10]:
# pip install numpy==2.1.0

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [1]:
import numpy as np

In [6]:
np.__version__

'2.1.0'

In [7]:
a = [1,2,3]
a


[1, 2, 3]

In [8]:
type(a)

list

In [9]:
np.array(a)

array([1, 2, 3])

In [12]:
type(np.array([1,2,3]))



numpy.ndarray

In [3]:
array = np.array([1, 2, 3])


array([11, 12, 13])

In [6]:
a=4
b ="abc"

c =np.array([1,2,3])
d =[1,2,3]
print(type(a))
print(type(b))
print(type(c))
print(type(d))

<class 'int'>
<class 'str'>
<class 'numpy.ndarray'>
<class 'list'>


In [38]:
c= np.array([1,2,3,4.,"343"])

In [39]:
print(np.array([1,2,3,4.22, "sds"]))

['1' '2' '3' '4.22' 'sds']


In [40]:
c.ndim

1

In [41]:
type(c)

numpy.ndarray

In [42]:
c.dtype


dtype('<U32')

In [14]:
c =np.array([1,2,3,4.0,"sdd"])
d =[1,2,3, "abc"]

print(c)
print(d)

['1' '2' '3' '4.0' 'sdd']
[1, 2, 3, 'abc']


In [15]:
c

array(['1', '2', '3', '4.0', 'sdd'], dtype='<U32')

In [43]:
np.array([[1,2,3]])

array([[1, 2, 3]])

In [46]:
a= np.array([[1,2,3]])
a.ndim

2

In [48]:
a= np.array([1,2,3])
a.ndim

1

In [51]:
print(a[0])

1


In [62]:

mm = np.array(
    [[
        [1, 2], 
        [5, 6], 
        [7, 8],
        [9, 10]
    ],
        [[3, 5], 
        [5, 6], 
        [7, 8],
        [9, 10]
    ]])

In [63]:
print(mm[0][0][1])

2


In [64]:
mm.ndim

3

In [3]:
np.arange(1,10,1 ,dtype="float32")

array([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

In [12]:
np.linspace(0,1, 5, dtype = np.float32)

array([0.  , 0.25, 0.5 , 0.75, 1.  ], dtype=float32)

In [ ]:
np.linspace()

In [13]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [15]:
np.ones((2,2,3))

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [16]:
np.ones((2,2,3)).ndim

3

In [76]:
np.zeros([2,4],dtype="float32")

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)

In [18]:
np.full((2,3),4)

array([[4, 4, 4],
       [4, 4, 4]])

In [19]:
np.random.rand(5)

array([0.02262355, 0.82973669, 0.18305348, 0.39009431, 0.39525756])

In [20]:
li =[4,5,7,89,0,[343,6,5,34],6,5,9]

In [26]:
li[5][3]

34

In [44]:

mm = np.array(
    [[
        [1, 2], 
        [5, 6], 
        [7, 8],
        [9, 10]
    ],
        [[3, 5], 
        [5, 6], 
        [7, 8],
        [9, 10]
    ],
        [[3, 5], 
        [5, 6], 
        [7, 8],
        [9, 10]
    ]])

In [29]:
mm.ndim

3

In [34]:
mm[1][2][1]

np.int64(8)

In [38]:
mm[1,2,1] =12
mm

array([[[ 1,  2],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]],

       [[ 3,  5],
        [ 5,  6],
        [ 7, 12],
        [ 9, 10]]])

In [43]:
li[2:6]

[7, 89, 0, [343, 6, 5, 34]]

In [42]:
li

[4, 5, 7, 89, 0, [343, 6, 5, 34], 6, 5, 9]

In [62]:
mm[1:2,2:3]

array([[[7, 8]]])

In [63]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [67]:
arr.reshape(4,4)

ValueError: cannot reshape array of size 12 into shape (4,4)

In [68]:
arr.reshape(4,-1)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [77]:
a = arr.reshape(4,3)

In [72]:
arr.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [73]:
arr.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [78]:
a.sum()

np.int64(78)

In [79]:
a.mean()

np.float64(6.5)

In [80]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [83]:
np.mean(a,axis=0)

array([5.5, 6.5, 7.5])

In [84]:
np.mean(a,axis=1)

array([ 2.,  5.,  8., 11.])

In [87]:
a=[
    [2,4],
    [4,6]]

b=[
    [3,5],
    [1,2]]



In [92]:
np.add(a,b)

array([[5, 9],
       [5, 8]])

In [93]:
a+b

[[2, 4], [4, 6], [3, 5], [1, 2]]

In [102]:
var = arr.reshape(-1) 
var 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [103]:
var >7

array([False, False, False, False, False, False, False,  True,  True,
        True,  True,  True])

In [104]:
var[var >7]

array([ 8,  9, 10, 11, 12])

In [105]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([10, 20, 30])

# Broadcasting the addition
result_broadcast = arr1 + arr2


In [106]:
result_broadcast

array([[11, 22, 33],
       [14, 25, 36]])

In [109]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([10, 20, 30])

In [110]:
arr1+arr2

array([[11, 22, 33],
       [14, 25, 36]])

In [111]:
# Matrix multiplication
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
result_matrix_mult = np.dot(matrix1, matrix2)
# Determinant
det = np.linalg.det(matrix1)
# Inverse
inv = np.linalg.inv(matrix1)


In [112]:
result_matrix_mult

array([[19, 22],
       [43, 50]])

In [113]:
det

np.float64(-2.0000000000000004)

In [114]:
19*50

950

In [115]:
43*22

946