How to create an empty and a full NumPy array?
Create a Numpy array filled with all zeros
Create a Numpy array filled with all ones
Check whether a Numpy array contains a specified row
How to Remove rows in Numpy array that contains non-n

In [1]:
import numpy as np


In [10]:
np.empty((2,3))
print(np.empty((2,3)))

[[9.34577196e-307 9.34598246e-307 1.60218491e-306]
 [1.69119873e-306 1.24611673e-306 1.05699581e-307]]


In [6]:
np.full((2,3),2)

array([[2, 2, 2],
       [2, 2, 2]])

In [4]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

# Check whether a Numpy array contains a specified row
How to Remove rows in Numpy array that contains non-numeric values?
Remove single-dimensional entries from the shape of an array
Find the number of occurrences of a sequence in a NumPy array
Find the most frequent value in a NumPy array
Combining a one and a two-dimensional NumPy Array
How to build an array of all combinations of two NumPy arrays?
How to add a border around a NumPy array?
How to compare two NumPy arrays?

In [1]:
np.empty((4,5))

NameError: name 'np' is not defined

In [ ]:
import random

In [4]:
import numpy as np
np.random.rand(3,4)

array([[0.71235138, 0.80223717, 0.55883451, 0.54939561],
       [0.84122796, 0.58320774, 0.82542714, 0.49769782],
       [0.10061013, 0.49773914, 0.88206313, 0.75569859]])

In [1]:
np.random.randn(3,4)

NameError: name 'np' is not defined

In [9]:
np.random.random((3,4))

array([[0.34603158, 0.82318641, 0.2259032 , 0.49996532],
       [0.80681576, 0.0582022 , 0.2934281 , 0.2928211 ],
       [0.48565176, 0.7040929 , 0.37432075, 0.2907416 ]])

In [16]:
np.random.randint(5,9,  size=(3,3))

array([[5, 5, 7],
       [6, 6, 8],
       [6, 6, 6]], dtype=int32)

In [10]:
np.arange(10,20,)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [13]:
np.linspace(1, 10, dtype = np.int32)

array([ 1,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  3,  3,  3,  3,  3,  3,
        4,  4,  4,  4,  4,  5,  5,  5,  5,  5,  5,  6,  6,  6,  6,  6,  7,
        7,  7,  7,  7,  7,  8,  8,  8,  8,  8,  9,  9,  9,  9,  9, 10],
      dtype=int32)

In [26]:
num =np.random.randint(5,9,  size=(3,3))
num

array([[5, 8, 5],
       [7, 6, 7],
       [5, 5, 6]], dtype=int32)

In [31]:
row = [4,6,8]

for i in num:
    print(i)

[5 8 5]
[7 6 7]
[5 5 6]


In [29]:
row =[5,5,6]

In [30]:
row in num.tolist()

True

In [32]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [8]:
import numpy as np
lst = np.array([1,4,7,8,3,45,6,'h','e','l',1,'o',99,101,79])

lenth= len(lst)

lenth

15

In [9]:
lst.reshape(3,5)

array([['1', '4', '7', '8', '3'],
       ['45', '6', 'h', 'e', 'l'],
       ['1', 'o', '99', '101', '79']], dtype='<U21')

In [13]:
lst.reshape(-1,4)

ValueError: cannot reshape array of size 15 into shape (4)

In [39]:
lenth= len(lst)

NameError: name 'lst' is not defined

1

In [38]:
i= 15
rows=4
actual=0
while(i):
    if(i%rows==0):
        print(i)
        actual=i
        break
    i+=1

16


In [37]:
lst = np.array([1,4,7,8,3,45,6,'h','e','l',1,'o',99,101,79])
print(len(lst))
j= np.zeros(actual- len(lst))
print(j)

15
[0.]


In [41]:
new_arr=np.append(lst,j)
len(new_arr)

16

In [42]:
new_arr.reshape(4,-1)

array([['1', '4', '7', '8'],
       ['3', '45', '6', 'h'],
       ['e', 'l', '1', 'o'],
       ['99', '101', '79', '0.0']], dtype='<U32')

: 

In [1]:
import numpy as np

In [2]:
np.linspace(0,1,4)

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [ ]:
# generate an array of 5 random numbers
array1 = np.random.rand(5)
np.random.randint(5,9,  size=(3,3))
np.random.random((3,4))
np.random.randn(3,4)
# create an empty array of length 4
array1 = np.empty(4)

In [7]:
np.random.randn(3,5)

array([[-0.8694834 , -0.22508074, -2.35885152, -0.75246472,  0.16878243],
       [ 0.30810508,  0.83616574, -1.92823916, -0.05573348,  0.80488056],
       [-0.51466157, -0.06797059, -1.04236648, -1.56221981, -0.9225249 ]])

In [16]:
abc = np.random.random((3,4))

In [14]:
abc

array([[0.52033936, 0.4424424 , 0.44638115, 0.33648693],
       [0.4406365 , 0.57328422, 0.37105856, 0.83846482],
       [0.93285966, 0.02965415, 0.4541336 , 0.7155244 ]])

In [12]:
abc.dtype

dtype('float64')

In [13]:
abc.astype('int32')

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int32)

In [15]:
abc.dtype

dtype('float64')

In [17]:
abc = abc.astype('int32')

In [18]:
abc.dtype

dtype('int32')



### 1. **Write to a File:**
   - **Problem**: Write a Python program that asks the user for their name and age. Write this information into a file called `user_info.txt`.
   - **Exception Handling**: Handle exceptions if the file cannot be opened or written.
   - **Hint**: Use `with open()` for handling file operations.


In [16]:
with open("user_info.txt", "w+") as f:
    name =input("enter your name")
    age = input("enter your age")
    f.write(f'name : {name}\n age :{age}')
    print("write done")


write done


In [22]:
with open("user_info.txt", "r+") as f:
    f.seek(0)
    print(f.readlines())

print("read success ")


['name : shahil\n', ' age :25']
read success 


In [23]:
with open("user_infod.txt", "r+") as f:
    f.seek(0)
    print(f.readlines())

print("read success ")

FileNotFoundError: [Errno 2] No such file or directory: 'user_infod.txt'

In [40]:
try:
    with open("user_info.txt", "r+") as f:
        f.seek(0)
        for w in f.readlines():
            print(w)
except PermissionError:
    print("permission denied  please 1st enable the permission by administrator")

except FileNotFoundError:
    print('File not found')

print("code success ")


name : 

 age :
code success 


In [38]:
# define Python user-defined exceptions
class InvalidAgeException(Exception):
    print("custom error")
# =======================================================================================
# you need to guess this number
number = 18

try:
    input_num = int(input("Enter a number: "))
    if input_num < number:
        raise InvalidAgeException
    else:
        print("Eligible to Vote")

except  ValueError:
    print("Invalid input. Please enter a valid number /not a string.")

except InvalidAgeException:
    print("Exception occurred: Invalid Age / age should >18")

except:
    print("unknown error")
    # link --> home

print("execution done")

custom error
Invalid input. Please enter a valid number /not a string.
execution done


In [34]:
if input_num < number:
    raise Exception("enter the age greater than 10")

Exception: enter the age greater than 10


Data written successfully.
