In [ ]:
import numpy as np

In [ ]:
arr = np.arange(1,13)
arr

In [ ]:
type(arr)

In [ ]:
arr.dtype

In [ ]:
arr.ndim

In [ ]:
arr.shape

In [ ]:
arr.size

In [ ]:
# data type change
arr.astype("f")

In [ ]:
arr = arr.astype("f")

In [ ]:
# indexing
arr

In [ ]:
arr[4]

In [ ]:
arr2d = np.array([[1,2,3],[4,5,6],[8,7,6]])
arr2d

In [ ]:
arr2d[1,1]

In [ ]:
arr2d[1,1:]

In [ ]:
# 3,6
arr2d[:2 ,2]

In [ ]:
arr3d = np.array([ [ [1,2,3],[4,5,6] ] ,[ [8,7,6],[9,4,6] ] ])
arr3d

In [ ]:
# access value 
# 2,5
arr3d[0,:, 1]
# 5,6
arr3d[0,1,1:]

In [ ]:
arr4 = np.array([1, 2, 3, 4], ndmin=2,dtype="f")
arr4

In [ ]:
# Negative Indexing
arr4[0,-2]

In [ ]:
# Converting Data Type on Existing Arrays

arr4 = arr4.astype("S")

## NumPy Array Reshaping

In [ ]:
arr

In [ ]:
arr5 = arr.reshape(3,4) # 2d convert

In [ ]:
arr5

In [ ]:
# 1D to 3d
arr6 = arr.reshape(2,2,3)
arr6

In [ ]:
arr6.reshape(12)

In [ ]:
# 3d to 2d
arr6.reshape(4,3)

In [ ]:
# unknown dimension --> use -1 in place of unknown value of dimensions
# -1
arr6.reshape(2,-1)

In [ ]:
arr6.reshape(2,-1,-1)

In [ ]:
arr6.reshape(2,-1,2)

In [ ]:
# Iterating Arrays
for i in arr:
    print(i)

In [ ]:
# Iterating Arrays
for i in arr2d:
    print(i)
    for j in i:
        print(j)

In [ ]:
# Iterating Arrays
for i in arr3d:
    # print(i)
    for j in i:
        for k in j:
            print(k)

In [ ]:
for i in np.nditer(arr3d):
    print(i)

In [ ]:
# Array operations
# Element-wise 
arr1 = np.array([1, 23, 3])
arr2 = np.array([4, 5, 6])
arr1+arr2

In [ ]:
arr1-arr2

In [ ]:
np.square(arr1)

In [ ]:
# Aggrigate functions
# sum
arr2d

In [ ]:
sum(arr2d)
arr2d.sum()

In [ ]:
arr2d.sum(axis=0)

In [ ]:
arr2d.sum(axis=1)

In [ ]:
arr3d

In [ ]:
arr3d.sum(axis=0)  # diffrent layer-wise

In [ ]:
arr3d.sum(axis=1)  # layer wise

In [ ]:
arr3d.sum(axis=2)  # row wise

In [ ]:
arr1+arr2

In [ ]:
arr1

In [ ]:
arr3 =np.array([2,3,4,5])
arr3

In [ ]:
arr1+arr3

## broadcast 

In [ ]:
arr4 = arr3.reshape(4,1)
arr4

In [ ]:
arr1+[3,4,3,4]

In [ ]:
arr1+arr4

In [ ]:
arr6 =np.array([[1,2,3],[2,3,4],[5,6,7]])
print(arr6)

In [ ]:
arr7 = np.array([1,2,3])
arr7

In [ ]:
arr6+arr7

In [ ]:
# https://jakevdp.github.io/PythonDataScienceHandbook/02.05-computation-on-arrays-broadcasting.html

In [ ]:
arr6 =np.array([[1,2,3],[2,3,4],[5,6,7],[8,7,6]])
print(arr6)

In [ ]:
arr6.shape

In [ ]:
# avg 
arr6.mean()

In [ ]:
arr6.mean()

For a 2-dimensional array, 

axis=0 refers to operations along the columns (vertically), 

while axis=1 refers to operations along the rows (horizontally).


In NumPy, the axis parameter in functions like np.sum(), np.mean(), 

In [ ]:
arr6.mean(axis=0)  # column wise avg

In [ ]:
arr6.mean(axis=1)  # # row wise avg

In [ ]:
# Convert N-Dimenstions array in 1D array
arr6
arr6.flatten()

In [ ]:
arr6.reshape(-1)

In [ ]:
# change the dimensions
arr6.T
arr6.transpose()

In [ ]:
arr7 = np.array([[3],[5],[7]])
arr7.shape

In [ ]:
arr7.transpose().shape

In [ ]:
# Concatenate use to append the data 
# but all array dimension must be same
arr_concatenated = np.concatenate((arr, arr))
arr_concatenated

In [ ]:
np.concatenate((arr6,arr6))

In [ ]:
# Examples
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a, b), axis=0)

# array([[1, 2],
#        [3, 4],
#        [5, 6]])

In [ ]:
np.concatenate((a, b.T), axis=1)
# array([[1, 2, 5],
#        [3, 4, 6]])

In [ ]:
np.concatenate((a, b), axis=None)
# array([1, 2, 3, 4, 5, 6])

In [ ]:
arr6.sort()
arr6

In [ ]:
np.sort(arr6)

In [ ]:
arr8 = np.random.random((3,5))
arr8

In [ ]:
np.sort(arr8,axis=0)

In [106]:
np.sort(arr8,axis=1)

array([[0.18593099, 0.32115159, 0.74715292, 0.80936725, 0.90774588],
       [0.34395063, 0.48531715, 0.56898797, 0.74681347, 0.81342352],
       [0.16843441, 0.399975  , 0.61090116, 0.65577509, 0.90518321]])

In [ ]:
arr8.sort()

In [ ]:
arr8

In [ ]:
arr8.argsort()

In [94]:
# Create an array
arr = np.array([50, 10, 40, 20, 30,452,120,123])

# 1. np.sort(): Sort an array in ascending order
sorted_arr = np.argsort(arr)
print("Sorted array:", sorted_arr)
# Output: [10 20 30 40 50]


Sorted array: [1 3 4 2 0 6 7 5]


In [98]:
arr.searchsorted([100])

array([5], dtype=int64)

In [100]:
arr.argmax()
arr.argmin()

1

In [112]:
# boolean indexing
arr

array([ 50,  10,  40,  20,  30, 452, 120, 123])

In [114]:
arr >40

array([ True, False, False, False, False,  True,  True,  True])

In [115]:
arr[arr >40]

array([ 50, 452, 120, 123])

In [118]:
np.isnan(arr)

array([False, False, False, False, False, False, False, False])

In [123]:
arr[6]= np.nan

ValueError: cannot convert float NaN to integer

In [124]:
import numpy as np

# Predefined array
arr = np.array([10, 20, 30, 40, 50], dtype=float)  # Must be float for np.nan

# Add null (np.nan) at specific index (e.g., index 2)
arr[2] = np.nan

print(arr)


[10. 20. nan 40. 50.]


In [127]:
np.isnan(arr).sum()

1

In [ ]:
# 2x+3y+z=1
# 4x+y+2z=2
# 3x+2y+3z=3

In [ ]:
# Coefficient matrix A
A = np.array([[2, 3, 1],
              [4, 1, 2],
              [3, 2, 3]])

In [ ]:

# Right-hand side vector b
b = np.array([1, 2, 3])

In [ ]:
# Solve the system of equations
solution = np.linalg.solve(A, b)