In [ ]:
import numpy as np 

In [ ]:
# array()
arr = np.array([45,6,9,0])
arr

In [ ]:
a= [5,6,78,4.54,"abc", True]
a

In [ ]:
arr2 = np.array([45,6,9,0,4.54,"ab54545334343434565wgresgredgs2453432343c", True])
arr2

In [ ]:
print(arr2)

In [ ]:
arr2.dtype

In [ ]:
# Dimensions 
# 0D
d1 = np.array(435)

In [ ]:
type(d1)

In [ ]:
d1.ndim

In [ ]:
print(arr)
arr.ndim

In [ ]:
arr2d = np.array([[34,56,76]])

In [ ]:
# show the number of row & col
arr2d.shape

In [ ]:
arr2d.size # count the number of elements in array

In [ ]:
arr2d.ndim  #show the number of Dimensions 

In [ ]:
# create 2row, 3col --> 2d array
arrd = np.array([[34,56,76],[4,5,6]])
arrd.shape

In [ ]:
print(arrd)

In [ ]:
arrd = np.array([[34,56,76],[4,6,]])

In [ ]:
arrd = np.array([[34,56,76],[4,6,np.inf]])

In [ ]:
arrd.shape

In [ ]:
print(arrd)

In [ ]:
arrd2 = np.array([[34,56,76],[4,6,np.inf], [4,5,6]])
arrd2.shape

In [ ]:
print(arrd2)

In [ ]:
arr3d= np.array([[[4,3,4],[4,5,6]] , [[37,8,9],[7,6,5]]])
arr3d.shape

In [ ]:
print(arr3d)

mat = np.matrix(l) #matris will be by default 2d

Linear algebra functions
Concatenation and splitting

In [ ]:
import numpy as np
np.matrix([3,4,5,6,7])

In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
y = arr.view()
print(x.base)
# print(y)
print(y.base)
print(x)


In [ ]:
print(id(arr))
print(id(x))
print(id(y))
print(y.base)
print(x.base)

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
# convert into 2d and 3d
a2d = arr.reshape(2,6)
a2d

In [ ]:
a3d = arr.reshape(2,3,2)
a3d

In [ ]:
# Unknown dimensions  --> for atleast 1 dimension unknown
ad = arr.reshape(3,-1)
ad

In [ ]:
# 2,3
#3d
arr.reshape(-1,2,3)

In [ ]:
# iterations
for i in arr:
    print(i)

In [ ]:
# iterations
for i in a2d:
    # print(i)
    for j in i:
        print(j)

In [ ]:
# iterations
for i in a3d:
    # print(i)
    for j in i:
        for k in j:
            print(k)

In [ ]:
# nditerator  --> use for iterating n-dimensions array in single loop
for i in np.nditer(a3d):
    print(i)

import numpy as np


In [ ]:

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
y = arr.view()
print(x.base)
print(y)
print(y.base)

✅ Broadcasting in NumPy
Broadcasting automatically expands smaller arrays to match the shape of larger ones in element-wise operations.

In [ ]:
a = np.array([0, 1, 2])
b = np.array([5, 5, 5])
a + b

In [ ]:
c= b.reshape(3,1)

In [ ]:
d = np.array([3,4,56,5])
d

In [ ]:
# https://jakevdp.github.io/PythonDataScienceHandbook/02.05-computation-on-arrays-broadcasting.html

SyntaxError: invalid syntax (1756088345.py, line 1)

In [ ]:
a+d
# here d in diffrent dimension so give you a broadcasting error
#  so we need to change a dimension to a to match the dimension of a

# rules of broadcasting
# 1. if the dimension is 1 then it can be broadcasted to any number of dimension
# 2. if 0 dimension then it can be broadcasted to any number of dimension
# 3: If in any dimension the sizes disagree and neither is equal to 1, an error is raised.

In [ ]:
e= d.reshape(4,1)
e

In [ ]:
a+e

In [52]:
M = np.ones((2, 3))
a = np.arange(3)

print(M)
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]
[0 1 2]


In [53]:
M+a

array([[1., 2., 3.],
       [1., 2., 3.]])

In [54]:
M = np.ones((3, 2))
a = np.arange(3)
M+a

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

Great question! Let's cover the **conditions of broadcasting in NumPy** in a clear and simple way.

---

### ✅ **Conditions of Broadcasting in NumPy**

Broadcasting allows NumPy to perform element-wise operations on arrays of **different shapes**, as long as certain **rules** are followed.

---

### 🧩 **Broadcasting Rules**

Suppose we have two arrays: `A` and `B`.

To broadcast them together:

1. **Align the shapes** **from the right** (pad with 1s on the left if needed).
2. **Dimensions are compatible if:**

   * They are equal, or
   * One of them is 1

---

### 🔢 **Example Scenarios**

#### ✅ **Valid Broadcasting**

```python
A.shape = (3, 1)
B.shape = (1, 4)
Result.shape = (3, 4)  # Compatible
```

Why valid?

* 1st dim: 3 vs 1 → OK (1 can be stretched)
* 2nd dim: 1 vs 4 → OK (1 can be stretched)

#### ❌ **Invalid Broadcasting**

```python
A.shape = (2, 3)
B.shape = (3, 2)
```

* 1st dim: 2 vs 3 → Not compatible
* 2nd dim: 3 vs 2 → Not compatible
  → **Error: operands could not be broadcast together**

---

### 📌 **Examples in Code**

#### Example 1: Broadcast scalar to array

```python
import numpy as np
A = np.array([1, 2, 3])
B = 5
print(A + B)  # [6 7 8]
```

#### Example 2: Broadcast 1D to 2D

```python
A = np.array([[1], [2], [3]])  # shape (3, 1)
B = np.array([10, 20, 30])     # shape (3,)
result = A + B                 # shape (3, 3)
print(result)
```

---

### 📌 Tip for Teaching:

When explaining broadcasting to students, show them how NumPy “virtually” expands the smaller array without actually copying data, which makes it memory-efficient.

---

Would you like visual diagrams or a worksheet for broadcasting examples?



# title
1. topic
    - new
2. 


## Linear Algebra

In [55]:
# 
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [57]:
arr.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [61]:
# Matrix multiplication
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
print(matrix1)
print(matrix2)
matrix1*matrix2

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


array([[ 5, 12],
       [21, 32]])

In [62]:
# dot product
matrix1@matrix2

array([[19, 22],
       [43, 50]])

In [63]:
np.dot(matrix1, matrix2)

array([[19, 22],
       [43, 50]])

In [65]:
# Determinant
det = np.linalg.det(matrix1)
det

-2.0000000000000004

In [66]:
# Inverse
inv = np.linalg.inv(matrix1)
inv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [67]:
A = np.array([[2, 3, 1],
              [4, 1, 2],
              [3, 2, 3]])


In [70]:
# Right-hand side vector b
b = np.array([1, 5, 3])


In [71]:
# Solve the system of equations
solution = np.linalg.solve(A, b)
solution

array([ 1.4, -0.6,  0. ])