## Linear Regresssion

In [25]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [26]:
# import the data
df  = pd.read_csv(r"c:\Users\hp\Desktop\class\loan_data_set.csv")
df

Loan_ID  Gender Married Dependents     Education Self_Employed  \
0    LP001002    Male      No          0      Graduate            No   
1    LP001003    Male     Yes          1      Graduate            No   
2    LP001005    Male     Yes          0      Graduate           Yes   
3    LP001006    Male     Yes          0  Not Graduate            No   
4    LP001008    Male      No          0      Graduate            No   
..        ...     ...     ...        ...           ...           ...   
609  LP002978  Female      No          0      Graduate            No   
610  LP002979    Male     Yes         3+      Graduate            No   
611  LP002983    Male     Yes          1      Graduate            No   
612  LP002984    Male     Yes          2      Graduate            No   
613  LP002990  Female      No          0      Graduate           Yes   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0               5849                0.0         NaN             360.0   
1               4583             1508.0       128.0             360.0   
2               3000                0.0        66.0             360.0   
3               2583             2358.0       120.0             360.0   
4               6000                0.0       141.0             360.0   
..               ...                ...         ...               ...   
609             2900                0.0        71.0             360.0   
610             4106                0.0        40.0             180.0   
611             8072              240.0       253.0             360.0   
612             7583                0.0       187.0             360.0   
613             4583                0.0       133.0             360.0   

     Credit_History Property_Area Loan_Status  
0               1.0         Urban           Y  
1               1.0         Rural           N  
2               1.0         Urban           Y  
3               1.0         Urban           Y  
4               1.0         Urban           Y  
..              ...           ...         ...  
609             1.0         Rural           Y  
610             1.0         Rural           Y  
611             1.0         Urban           Y  
612             1.0         Urban           Y  
613             0.0     Semiurban           N  

[614 rows x 13 columns]

In [27]:
# info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Loan_ID            614 non-null    object 
 1   Gender             601 non-null    object 
 2   Married            611 non-null    object 
 3   Dependents         599 non-null    object 
 4   Education          614 non-null    object 
 5   Self_Employed      582 non-null    object 
 6   ApplicantIncome    614 non-null    int64  
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         592 non-null    float64
 9   Loan_Amount_Term   600 non-null    float64
 10  Credit_History     564 non-null    float64
 11  Property_Area      614 non-null    object 
 12  Loan_Status        614 non-null    object 
dtypes: float64(4), int64(1), object(8)
memory usage: 62.5+ KB


In [28]:
df.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [29]:
df

Loan_ID  Gender Married Dependents     Education Self_Employed  \
0    LP001002    Male      No          0      Graduate            No   
1    LP001003    Male     Yes          1      Graduate            No   
2    LP001005    Male     Yes          0      Graduate           Yes   
3    LP001006    Male     Yes          0  Not Graduate            No   
4    LP001008    Male      No          0      Graduate            No   
..        ...     ...     ...        ...           ...           ...   
609  LP002978  Female      No          0      Graduate            No   
610  LP002979    Male     Yes         3+      Graduate            No   
611  LP002983    Male     Yes          1      Graduate            No   
612  LP002984    Male     Yes          2      Graduate            No   
613  LP002990  Female      No          0      Graduate           Yes   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0               5849                0.0         NaN             360.0   
1               4583             1508.0       128.0             360.0   
2               3000                0.0        66.0             360.0   
3               2583             2358.0       120.0             360.0   
4               6000                0.0       141.0             360.0   
..               ...                ...         ...               ...   
609             2900                0.0        71.0             360.0   
610             4106                0.0        40.0             180.0   
611             8072              240.0       253.0             360.0   
612             7583                0.0       187.0             360.0   
613             4583                0.0       133.0             360.0   

     Credit_History Property_Area Loan_Status  
0               1.0         Urban           Y  
1               1.0         Rural           N  
2               1.0         Urban           Y  
3               1.0         Urban           Y  
4               1.0         Urban           Y  
..              ...           ...         ...  
609             1.0         Rural           Y  
610             1.0         Rural           Y  
611             1.0         Urban           Y  
612             1.0         Urban           Y  
613             0.0     Semiurban           N  

[614 rows x 13 columns]

In [5]:
df2 = df.copy()
df2.dropna(axis=0, inplace=True)

In [30]:
df2.isnull().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [ ]:
df2.describe()

In [ ]:
x = df2[["ApplicantIncome"]]
x

In [ ]:
y = df2[["LoanAmount"]]
y

In [31]:
# split the data into training and testing sets
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=.20, random_state=42)

In [32]:
x_train

ApplicantIncome  CoapplicantIncome  Loan_Amount_Term
172             3522                0.0             180.0
288             4124                0.0             360.0
607             3987             1411.0             360.0
55              2708             1167.0             360.0
461             7740                0.0             180.0
..               ...                ...               ...
141             5417                0.0             360.0
350             9083                0.0             360.0
445             3466             1210.0             360.0
558             3887             2669.0             360.0
137             3316             3500.0             360.0

[384 rows x 3 columns]

In [33]:
x_test

ApplicantIncome  CoapplicantIncome  Loan_Amount_Term
92              3273             1820.0             360.0
529             6783                0.0             360.0
505             3510             4416.0             360.0
358             3000             1666.0             480.0
512             3283             2035.0             360.0
..               ...                ...               ...
281             3927              800.0             360.0
299             2014             2925.0             360.0
522             5677             1424.0             360.0
33              3500             1667.0             360.0
537             3617                0.0             360.0

[96 rows x 3 columns]

In [34]:
# simple linear regression
# y= mx+c
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model

LinearRegression()

In [35]:
# find the value of m and c
# y=mx+ c
model.fit(x_train, y_train)

LinearRegression()

In [36]:
# m/ slope/ coefficient
model.coef_

array([[0.00640719, 0.00680412, 0.05453281]])

In [37]:
# intcept/ c 
model.intercept_

array([79.21974979])

In [17]:
# y = o.oo6x + 110.69

In [38]:
# for testing 
# pridict the x_test 

y_predicted = model.predict(x_test)

In [ ]:
y_test

## find or show the error difference

In [39]:
from sklearn.metrics import mean_absolute_error, mean_squared_error,root_mean_squared_error
mean_absolute_error(y_test, y_predicted)

np.float64(46.825346837716125)

In [40]:
mean_squared_error(y_test, y_predicted)

np.float64(5545.183719244174)

In [41]:
root_mean_squared_error(y_test, y_predicted)

np.float64(74.46599035294014)

In [42]:
from sklearn.metrics import r2_score
r2_score(y_test,y_predicted)

# variance bt actual and predicted values ratio --> accuracy

0.33997366042265087

In [53]:
# MLR
df2.drop("Loan_ID",axis=1,inplace= True)

In [ ]:
df2.isnull().sum()

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le.fit_transform(df2["Gender"])
df2["Gender"] = le.transform(df2["Gender"])
df2["Gender"]

In [ ]:
for  i in df.columns:
    if df2[i].dtype =="O":        
        df2[i] = le.transform(df2[i])

df2

In [ ]:
df2

In [ ]:
x

In [ ]:
# split data in x and y
x = df2.drop("LoanAmount",axis=1)
x
y = df2[["LoanAmount"]]
y

In [72]:
# train or test 
x_train, x_test, y_train, y_test = train_test_split(x, y , test_size=.20, random_state=33)

In [ ]:
model2 = LinearRegression()
model2.fit(x_train, y_train)

In [79]:
model2.coef_


array([[-5.81102937e+00,  2.25564137e+01,  7.23491664e+00,
        -1.90517137e+01,  1.20758747e+00,  9.03666660e-03,
         6.44590946e-03,  7.41831501e-02, -4.88436542e+00,
        -1.36200776e+01, -1.34572672e+01]])

In [80]:
model2.intercept_

array([76.3462937])

In [77]:
y_predict = model2.predict(x_test)
mean_squared_error(y_test, y_predict)

np.float64(5743.634057224197)

In [78]:
r2_score(y_test, y_predict)

0.014038634896614943

In [85]:
# y --> categorical variable
x = df2.drop("Loan_Status", axis=1)
x
y = df2[["Loan_Status"]]
y

Loan_Status
1              0
2              1
3              1
4              1
5              1
..           ...
609            1
610            1
611            1
612            1
613            0

[480 rows x 1 columns]

In [88]:
from sklearn.linear_model import LogisticRegression

x_train, x_test , y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

lr = LogisticRegression( solver="liblinear")

lr.fit(x_train, y_train)

C:\Users\hp\AppData\Roaming\Python\Python311\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(solver='liblinear')

In [89]:
y_predict = lr.predict(x_test)
y_predict

array([1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1])

In [90]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

accuracy_score(y_test, y_predict)

0.8229166666666666

In [91]:
confusion_matrix(y_test, y_predict)

array([[11, 17],
       [ 0, 68]])

In [93]:
print(classification_report(y_test, y_predict))

              precision    recall  f1-score   support

           0       1.00      0.39      0.56        28
           1       0.80      1.00      0.89        68

    accuracy                           0.82        96
   macro avg       0.90      0.70      0.73        96
weighted avg       0.86      0.82      0.79        96

