## Numpy

In [1]:
list1 =[1,2,3,4]
list1

[1, 2, 3, 4]

In [2]:
# Array
import numpy as np
arr = np.array([45,6,7,8,9])
arr

array([45,  6,  7,  8,  9])

In [ ]:
#  datatypes 
# list hetrogenious 
# array is homogenious

In [3]:
list1.append("abc")

In [4]:
list1

[1, 2, 3, 4, 'abc']

In [6]:
np.append(arr, "aerwsdfrgfgddgrtdfgchghfjhgjnghjkuhkmuj,ji,jibc")

array(['45', '6', '7', '8', '9',
       'aerwsdfrgfgddgrtdfgchghfjhgjnghjkuhkmuj,ji,jibc'], dtype='<U47')

In [7]:
# check the datatypes use type
type(list1)

list

In [8]:
type(arr)

numpy.ndarray

In [9]:
# dimenstions in array 
# 0D --> single number
# 1D -> single row /single column
# 2D --> row and columns form
# 3D --> layer based
# nD ......
arr.ndim  # check the number of dimentions

1

In [10]:
arr

array([45,  6,  7,  8,  9])

In [11]:
np.array(4)

array(4)

In [12]:
np.array(4).ndim

0

In [13]:
# create 2d array
arr2d = np.array([[4,5,6,7]])
arr2d

array([[4, 5, 6, 7]])

In [14]:
arr2d.ndim

2

In [15]:
np.array([[4,5,6,7],[34,43,5,6]])

array([[ 4,  5,  6,  7],
       [34, 43,  5,  6]])

In [16]:
# checek the shape (columns, rows)
arr2d.shape

(1, 4)

In [17]:
# COUNT THE NUMBER OF ELEMENT IN ARRAY
arr2d.size

4

In [18]:
arr2d

array([[4, 5, 6, 7]])

In [22]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 6, 6]]])
print(arr)


[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 6 6]]]


In [20]:
arr.shape

(2, 2, 3)

In [26]:
# create custom data types and custom dimentions in array
arr3 = np.array((34,6,7,8), dtype="U", ndmin=10)
arr3

array([[[[[[[[[['34', '6', '7', '8']]]]]]]]]], dtype='<U2')

In [28]:

arr4 = np.array((34,6,7,8,4,5))
arr4

array([34,  6,  7,  8,  4,  5])

#### Indexing and slicing

In [29]:
# indexing 
arr4[3]

np.int64(8)

In [30]:
# negative indexing
arr4[-4]

np.int64(7)

In [32]:
arr4

array([34,  6,  7,  8,  4,  5])

In [31]:
# slicing  
# syntax name[start: stop : step]
arr4[2:4]

array([7, 8])

In [33]:
arr4[2: ]

array([7, 8, 4, 5])

In [39]:
arr2d = np.array([[2,3,45,5], [34,5,6,78]])
arr2d

array([[ 2,  3, 45,  5],
       [34,  5,  6, 78]])

In [40]:
# 2d indexing and slicing
arr2d[1]

array([34,  5,  6, 78])

In [41]:
arr2d[1][2]

np.int64(6)

In [42]:
arr2d[1,2]

np.int64(6)

In [44]:
arr2d[0:,2:]

array([[45,  5],
       [ 6, 78]])

In [46]:
# Converting Data Type on Existing Arrays
arr2d.astype("f",)

array([[ 2.,  3., 45.,  5.],
       [34.,  5.,  6., 78.]], dtype=float32)

# Reshaping


In [47]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [48]:
newarr.ndim

2

In [57]:
arr.reshape(2, 2, 3)  # convert into 1D into 3D 

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [60]:
# flatten for convert into 1D
arr2d

array([[ 2,  3, 45,  5],
       [34,  5,  6, 78]])

In [61]:
arr2d.flatten()

array([ 2,  3, 45,  5, 34,  5,  6, 78])