In [1]:
# Import library numpy
pip install numpy 

import numpy as np #2005 by Travis Oliphant 

In [2]:
# check the version
np.__version__

'1.24.3'

In [3]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly 

An array is a data structure that stores a collection of elements, typically of the same data type, in a contiguous block of memory. Arrays allow you to store multiple values in a single variable and access these values using indices. In most programming languages, including Python (via NumPy), arrays are used for efficiently storing and manipulating numerical data.

### Characteristics of Arrays:
1. **Fixed Size:**
   - Once an array is created, its size is fixed, meaning it cannot grow or shrink dynamically like Python lists. The number of elements (length) in an array is set at the time of its creation.

2. **Homogeneous Elements:**
   - All elements in an array must be of the same data type (e.g., all integers, all floats, etc.). This makes operations on arrays more efficient.

3. **Contiguous Memory Allocation:**
   - Elements in an array are stored in contiguous memory locations, which allows for fast access and efficient memory use.

4. **Indexing:**
   - Arrays use zero-based indexing, meaning the first element is accessed with index 0, the second with index 1, and so on. This allows for direct access to any element in constant time (O(1)).

5. **Efficient Computation:**
   - Due to the fixed size and contiguous memory allocation, arrays allow for efficient computation, particularly in numerical operations where large datasets are involved.

### Types of Arrays:
- **One-Dimensional Array (1D Array):**
  - A linear array where elements are arranged in a single row.
  - Example: `[1, 2, 3, 4, 5]`

- **Two-Dimensional Array (2D Array):**
  - An array of arrays, often visualized as a matrix with rows and columns.
  - Example: 
    ```
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
    ```

- **Multi-Dimensional Array:**
  - An array with more than two dimensions, such as a 3D array, which can represent a cube of data.
  - Example: A 3x3x3 cube.

### Arrays in NumPy:
In Python, the basic array structure is the list, but for more advanced numerical operations, the NumPy library is commonly used. NumPy arrays (`ndarray`) provide additional functionality and performance benefits over Python lists, making them ideal for scientific computing.

#### Creating Arrays in NumPy:
```python
import numpy as np

# 1D Array
array_1d = np.array([1, 2, 3, 4, 5])

# 2D Array (Matrix)
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# 3D Array
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print("1D Array:\n", array_1d)
print("2D Array:\n", array_2d)
print("3D Array:\n", array_3d)
```

### Operations on Arrays:
- **Element-wise Operations:**
  - You can perform mathematical operations on arrays element-wise.
  ```python
  array = np.array([1, 2, 3, 4])
  result = array + 10  # Adds 10 to each element
  ```

- **Matrix Operations:**
  - Arrays can represent matrices, allowing for operations like matrix multiplication.
  ```python
  matrix1 = np.array([[1, 2], [3, 4]])
  matrix2 = np.array([[5, 6], [7, 8]])
  result = np.dot(matrix1, matrix2)  # Matrix multiplication
  ```

- **Indexing and Slicing:**
  - You can access individual elements or subarrays using indexing and slicing.
  ```python
  array = np.array([1, 2, 3, 4, 5])
  element = array[2]  # Accessing the 3rd element (index 2)
  subarray = array[1:4]  # Slicing from index 1 to 3
  ```

### Use Cases of Arrays:
1. **Data Storage:**
   - Arrays are used to store large datasets, such as time series data, image data, or any numerical data, efficiently in memory.

2. **Mathematical Computations:**
   - Arrays are ideal for performing mathematical computations, such as vector operations, matrix multiplications, and solving systems of equations.

3. **Scientific Simulations:**
   - In scientific research, arrays are used to simulate physical systems, perform numerical analysis, and run experiments with large datasets.

4. **Image Processing:**
   - Images are represented as multi-dimensional arrays (e.g., 2D for grayscale images, 3D for color images), enabling operations like filtering, transformation, and enhancement.

### Conclusion:
Arrays are a fundamental data structure in programming, particularly in numerical computing and data analysis. In Python, while lists can be used as basic arrays, NumPy provides more powerful and efficient array structures (`ndarray`) for handling large datasets and performing complex numerical operations.

In [ ]:
#Why numpy
#-mathematical function
#Faster

In [4]:
l = [1, 2, 3, 4, 5]

In [10]:
arr = np.array(l)

In [12]:
arr

array([1, 2, 3, 4, 5])

In [6]:
type(np.array(l))

numpy.ndarray

In [8]:
type(np.array(l))

numpy.ndarray

In [11]:
arr.ndim

1

In [14]:
import numpy as np
l = [1, 2, 3, 4, 5, "arr"]
arr = np.array(l)
arr

array(['1', '2', '3', '4', '5', 'arr'], dtype='<U21')

In [15]:
arr.ndim

1

In [16]:
arr

array(['1', '2', '3', '4', '5', 'arr'], dtype='<U21')

In [31]:
p = np.array([[[[[
    [1, 2, 3],[1,2,3],[3,4,5]
 ] ]] ]])

In [28]:
p.ndim

6

In [34]:
arr1 = np.array([1, 2, 3])

In [36]:
arr2 = np.array([4,5,6])

In [37]:
arr1+arr2

array([5, 7, 9])

In [38]:
arr1-arr2

array([-3, -3, -3])

In [18]:
arr1.ndim

2

In [41]:
l = [1, 2, 3, 4]

In [42]:
np.array(l)

array([1, 2, 3, 4])

In [43]:
mat = np.matrix(l) #matris will be by default 2d

In [44]:
mat

matrix([[1, 2, 3, 4]])

In [68]:
np.matrix(
    [
    [1, 2], 
    [5, 6]
    ])

matrix([[1, 2],
        [5, 6]])

In [46]:
np.array(
    [[
        [1, 2], 
        [5, 6], 
        [7, 8]
    ]])

array([[[1, 2],
        [5, 6],
        [7, 8]]])

In [48]:
d = [[[1, 2], [5, 6], [7, 8]]]

In [50]:
type(d)


list

In [27]:
#more way to convert to array
np.asarray([[[1, 2], [5, 6], [7, 8]]])

array([[[1, 2],
        [5, 6],
        [7, 8]]])

In [28]:
np.asanyarray([[[1, 2], [5, 6], [7, 8]]]) #Convert the input to an ndarray, but pass ndarray subclasses through.

array([[[1, 2],
        [5, 6],
        [7, 8]]])

In [30]:
mat

matrix([[1, 2, 3, 4]])

In [31]:
np.asanyarray(mat)

matrix([[1, 2, 3, 4]])

In [32]:
np.asarray([[[1, 2], [5, 6], [7, 8]]])

array([[[1, 2],
        [5, 6],
        [7, 8]]])

In [33]:
np.array([[[1, 2], [5, 6], [7, 8]]])

array([[[1, 2],
        [5, 6],
        [7, 8]]])

In [34]:
t = ([1, 2, 3], [4, 5, 6])
type(t)

tuple

In [35]:
np.array(t)

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
a = 5
np.array(a)

array(5)

In [37]:
l = [1, 2, 3, 4, 5]
arr = np.array(l)
arr

array([1, 2, 3, 4, 5])

In [41]:
a = arr

In [42]:
a

array([1, 2, 3, 4, 5])

In [43]:
arr[0] = 1000

In [44]:
arr

array([1000,    2,    3,    4,    5])

In [45]:
a

array([1000,    2,    3,    4,    5])

In [46]:
a

array([1000,    2,    3,    4,    5])

In [47]:
b = a.copy()
b[0] = 2000

In [48]:
b

array([2000,    2,    3,    4,    5])

In [49]:
a

array([1000,    2,    3,    4,    5])

In [ ]:
#to create array >> .array, .asasrray, .asanyarray, deep copy, shallow copy

In [ ]:
#There are multiple ways to generating arrays

In [50]:
np.fromfunction(lambda i, j : i==j, (3, 3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [51]:
arr

array(['1', '2', '3', '4', '5', 'arr'], dtype='<U21')

In [52]:
arr.shape

(6,)

In [61]:
arr = np.array(['1', '2', '3', '4', '5', 'arr'])

In [65]:
arr.ndim

1

In [73]:
mm = np.array(
    [
        [1, 2], 
        [5, 6], 
        [7, 8],
        [9, 10]
    ])

In [77]:
mm = np.array(
    [[[
        [1, 2], 
        [5, 6], 
        [7, 8],
        [9, 10]
    ]]])

In [78]:
mm.shape

(1, 1, 4, 2)

In [67]:
arr.size

6

In [55]:
arr1.size

3

In [61]:
np.fromfunction(lambda i, j : i==j, (3, 3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [62]:
np.fromfunction(lambda i, j : i*j, (3, 3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [64]:
for i in range(5):
    print(i)

0
1
2
3
4


In [65]:
[i for i in range(5)]

[0, 1, 2, 3, 4]

In [66]:
list(i for i in range(5))

[0, 1, 2, 3, 4]

In [67]:
list(range(5))

[0, 1, 2, 3, 4]

In [83]:
iterable = (i*i for i in range(5))

In [84]:
np.fromiter(iterable, int)

array([ 0,  1,  4,  9, 16])

In [81]:
np.fromstring('23 34 67', sep = ' ')

array([23., 34., 67.])

In [80]:
np.fromstring('23,34,67', sep = ',')

array([23., 34., 67.])

In [79]:
np.fromstring('Suhani,Ajay,Anwesha', sep = ',')

C:\Users\hp\AppData\Local\Temp\ipykernel_11356\4232903791.py:1: DeprecationWarning: string or file could not be read to its end due to unmatched data; this will raise a ValueError in the future.
  np.fromstring('Suhani,Ajay,Anwesha', sep = ',')


array([], dtype=float64)

In [86]:
arr

array([1000,    2,    3,    4,    5])

In [87]:
arr.size

5

In [88]:
arr.shape

(5,)

In [89]:
arr.dtype

dtype('int32')

In [92]:
l = [1, 2,3, "Ajay"]
arr = np.array(l)
arr.dtype

dtype('<U11')

In [93]:
arr

array(['1', '2', '3', 'Ajay'], dtype='<U11')

In [94]:
list(range(5))

[0, 1, 2, 3, 4]

In [95]:
range(5)

range(0, 5)

In [99]:
list(range(1.0, 2.10))

TypeError: 'float' object cannot be interpreted as an integer

In [102]:
list(np.arange(0.1, 10.2, 0.1))

[0.1,
 0.2,
 0.30000000000000004,
 0.4,
 0.5,
 0.6,
 0.7000000000000001,
 0.8,
 0.9,
 1.0,
 1.1,
 1.2000000000000002,
 1.3000000000000003,
 1.4000000000000001,
 1.5000000000000002,
 1.6,
 1.7000000000000002,
 1.8000000000000003,
 1.9000000000000001,
 2.0,
 2.1,
 2.2,
 2.3000000000000003,
 2.4000000000000004,
 2.5000000000000004,
 2.6,
 2.7,
 2.8000000000000003,
 2.9000000000000004,
 3.0000000000000004,
 3.1,
 3.2,
 3.3000000000000003,
 3.4000000000000004,
 3.5000000000000004,
 3.6,
 3.7,
 3.8000000000000003,
 3.9000000000000004,
 4.0,
 4.1,
 4.2,
 4.3,
 4.3999999999999995,
 4.5,
 4.6,
 4.7,
 4.8,
 4.9,
 5.0,
 5.1,
 5.2,
 5.3,
 5.4,
 5.5,
 5.6,
 5.7,
 5.8,
 5.9,
 6.0,
 6.1,
 6.2,
 6.3,
 6.4,
 6.5,
 6.6,
 6.7,
 6.8,
 6.9,
 7.0,
 7.1,
 7.2,
 7.3,
 7.4,
 7.5,
 7.6,
 7.7,
 7.8,
 7.9,
 8.0,
 8.1,
 8.2,
 8.3,
 8.4,
 8.5,
 8.6,
 8.7,
 8.8,
 8.9,
 9.0,
 9.1,
 9.2,
 9.3,
 9.4,
 9.5,
 9.6,
 9.700000000000001,
 9.8,
 9.9,
 10.0,
 10.1]

In [170]:
np.linspace(1, 5, 10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [109]:
np.logspace(1, 5, 10, base = 2)

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [110]:
np.logspace(1, 5, 10, base = 10)

array([1.00000000e+01, 2.78255940e+01, 7.74263683e+01, 2.15443469e+02,
       5.99484250e+02, 1.66810054e+03, 4.64158883e+03, 1.29154967e+04,
       3.59381366e+04, 1.00000000e+05])

In [158]:
arr1 = np.zeros(5)
arr1.shape

(5,)

In [159]:
arr1

array([0., 0., 0., 0., 0.])

In [160]:
arr1.ndim

1

In [161]:
arr2 = np.zeros((3, 4))
arr2.shape

(3, 4)

In [162]:
arr2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [119]:
arr2.ndim

2

In [163]:
arr3 = np.zeros((1, 3, 4))
arr3.shape

(1, 3, 4)

In [164]:
arr3.ndim

3

In [167]:
arr4 = np.zeros((1, 1, 3, 4))
arr4.shape

(1, 1, 3, 4)

In [168]:
arr4.ndim

4

In [169]:
arr4

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [130]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [139]:
arr = np.ones((3,4))

In [140]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [141]:
arr+5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [143]:
arr * 3

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

In [ ]:
np.array([[[[[[[[[[[[[[1, 1, 1, 1, ,1 ]]]]]]]]]]]]]])

In [144]:
np.twos((2,3))

AttributeError: module 'numpy' has no attribute 'twos'

In [155]:
l = [1, 2,3, 4,5, "Prince"]
arr = np.array(l)
arr.dtype

dtype('<U11')

In [156]:
arr

array(['1', '2', '3', '4', '5', 'Prince'], dtype='<U11')